### ISSUE TITLE
What to do when sending a message to a no longer existing smart connector.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#108]
In GitLab by @barry.nouwt.tno.nl on Feb 5, 2021, 13:45

Currently, this throws the following exception:

```
java.io.IOException: There is no KnowledgeBase with ID https://www.tno.nl/kb1
	at interconnect.ke.runtime.JvmOnlyMessageDispatcher$SmartConnectorHandler.send(JvmOnlyMessageDispatcher.java:54)
	at interconnect.ke.sc.MessageRouterImpl.sendAskMessage(MessageRouterImpl.java:48)
	at interconnect.ke.sc.SerialMatchingProcessor.checkOtherKnowledgeInteraction(SerialMatchingProcessor.java:80)
	at interconnect.ke.sc.SerialMatchingProcessor.processAskInteraction(SerialMatchingProcessor.java:53)
	at interconnect.ke.sc.InteractionProcessorImpl.processAskFromKnowledgeBase(InteractionProcessorImpl.java:70)
	at interconnect.ke.sc.SmartConnectorImpl.ask(SmartConnectorImpl.java:300)
	at interconnect.ke.sc.SmartConnectorImpl.ask(SmartConnectorImpl.java:317)
	at interconnect.ke.admin.AdminUI.lambda$0(AdminUI.java:70)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

This happens for example when you stop all KBs, while the AdminUI KB just wants to retrieve info about them. We might want to only give a warning about this?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 8, 2021, 13:46

When deleting two KBs simultaneously from via the REST API, the following error was shown on the Server. The KB for which the Smart Connector was stopped was stuck in a blocking DELETE call to the REST API. (This happens in the simple python client I created for the Workshop). We should check out all the usages of futures in our code and make sure we let the Future complete exceptionally...

```
2021-04-08 15:42:44:121 +0200 [pool-4-thread-4] ERROR JvmOnlyMessageDispatcher - No errors should occur.
java.lang.NullPointerException
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.MessageRouterImpl.handlePostMessage(MessageRouterImpl.java:111)
	at eu.interconnectproject.knowledge_engine.smartconnector.runtime.JvmOnlyMessageDispatcher$SmartConnectorHandler.lambda$send$0(JvmOnlyMessageDispatcher.java:65)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 30, 2021, 10:58

marked this issue as related to #172

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Oct 29, 2021, 12:10

Solution: remove the IOException from the warning, because it does not really add anything.

```
2021-10-01 12:50:56:134 +0100 [qtp1500056228-52] WARN MessageRouterImpl-kb_tiko_ans_2_r - Could not send reply to message 0f6dda14-bb45-4eea-bc2b-e25ec6f52674
java.io.IOException: Could not send message 5a05a3fb-75f8-4b51-b741-050d44fbccb9, the Knowledge Base https://ke.interconnectproject.eu/adapter/9a04ecfa09c873c18bb155546dec2f0c40d492c1f415e4f1b6a750a7a458aa8b7c7079c9d33e2c58e29210dbe40e7d599c9846b440913d3e7e953a4d41418f71 is not known
	at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.sendToLocalOrRemoteSmartConnector(MessageDispatcher.java:223)
	at eu.knowledge.engine.smartconnector.runtime.messaging.LocalSmartConnectorConnection.send(LocalSmartConnectorConnection.java:78)
	at eu.knowledge.engine.smartconnector.impl.MessageRouterImpl.lambda$handlePostMessage$1(MessageRouterImpl.java:109)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.finishHandleRequest(RestKnowledgeBase.java:293)
	at eu.knowledge.engine.rest.api.impl.ReactiveApiServiceImpl.scHandlePost(ReactiveApiServiceImpl.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.io.IOException: Could not send message c83fc616-d797-440e-92bf-d31f32928383, the Knowledge Base https://ke.interconnectproject.eu/adapter/d1492e767e72c22826538f420807ceabc1803eb46260816efa0483dc7a359e4b5e1fc1bae9d1b607d6f89d408a7ae76700808b1362ffcb4a8b90c0098e30187d is not known
	at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.sendToLocalOrRemoteSmartConnector(MessageDispatcher.java:223)
	at eu.knowledge.engine.smartconnector.runtime.messaging.LocalSmartConnectorConnection.send(LocalSmartConnectorConnection.java:78)
	at eu.knowledge.engine.smartconnector.impl.MessageRouterImpl.lambda$handlePostMessage$1(MessageRouterImpl.java:109)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.finishHandleRequest(RestKnowledgeBase.java:293)
	at eu.knowledge.engine.rest.api.impl.ReactiveApiServiceImpl.scHandlePost(ReactiveApiServiceImpl.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 19, 2022, 10:14

marked this issue as related to #257

**Comment by bnouwt** [comment]
Also in distributed mode, this happens and prints big stack traces in the log that look very scary but maybe are not entirely necessary:

```
2024-02-09 14:07:16:035 +0000 [qtp122568328-37158] WARN RemoteMessageReceiver - Error while handling incoming message
java.io.IOException: Could not deliver message e430fda9-58e5-4372-ba22-d41f3d5c412b, the Knowledge Base http://www.example.org/kb-b09c4c0c-9ba0-4d40-8f01-14bc247854f4 is not known locally
   at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.deliverToLocalSmartConnector(MessageDispatcher.java:256)
   at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteMessageReceiver.handleMessage(RemoteMessageReceiver.java:40)
   at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteMessageReceiver.messagingAskmessagePost(RemoteMessageReceiver.java:57)
   at eu.knowledge.engine.smartconnector.runtime.messaging.inter_ker.api.MessagingApi.messagingAskmessagePost(MessagingApi.java:88)
   at jdk.internal.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
   at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
   at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
   at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
   at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
   at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
   at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
   at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
   at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
   at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
   at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
   at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
   at org.eclipse.jetty.server.Server.handle(Server.java:516)
   at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
   at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
   at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
```

**Comment by bnouwt** [comment]
This issue of verbose error messages was resolved in version 1.4.0 in the `ReasonerProcessor`.
