### ISSUE TITLE
Re-adding a previously deleted KB to the REST Server causes a status 500.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#174]
In GitLab by @barry.nouwt.tno.nl on Apr 12, 2021, 09:17

Issue from @aleksandar.tomcic.vizlore.com 

It seems the problem happens when a Knowledge Base has been deleted and you want to add a KB with the same ID again afterwards.

A temporary workaround is to not use a the same Knowledge Base Id after deleting a KB.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 12, 2021, 09:17

added [1 design](/interconnect/knowledge-engine/-/issues/160/designs?version=3)

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 12, 2021, 10:24

This problem does not happen everytime you add a KB after it has been deleted. I cannot reproduce it locally (yet). I did look at the log file of the instance of INESC TEC server and saw a lot of Exceptions like:

```
2021-04-09 13:29:57:864 +0100 [qtp1450821318-11450] WARN ServletHandler - 
javax.servlet.ServletException: java.lang.IllegalArgumentException: There already is a smart connector registered with ID http://www.tno.nl/kb2
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: There already is a smart connector registered with ID http://www.tno.nl/kb2
	at eu.interconnectproject.knowledge_engine.smartconnector.runtime.LocalSmartConnectorRegistryImpl.register(LocalSmartConnectorRegistryImpl.java:36)
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.SmartConnectorImpl.<init>(SmartConnectorImpl.java:89)
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.SmartConnectorBuilder.create(SmartConnectorBuilder.java:21)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.<init>(RestKnowledgeBase.java:142)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBaseManager.createKB(RestKnowledgeBaseManager.java:36)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.SmartConnectorLifeCycleApiServiceImpl.scPost(SmartConnectorLifeCycleApiServiceImpl.java:97)
	at eu.interconnectproject.knowledge_engine.rest.api.SmartConnectorLifeCycleApi.scPost(SmartConnectorLifeCycleApi.java:96)
	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	... 18 more
```

What might be the case is that sometimes, when you delete a KB, it does not get deleted from the registry correctly. Is this possible?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 12, 2021, 10:57

Maybe the problem occurs when stopping a Knowledge Base it wants to post the remove knowledge base meta messages, but if this blocks indefinitely then it will never be unregistered. Look at the code in the SmartconnectorImpl.stop() method.

Maybe we should double check that all futures that we use, use the completeExceptionally whenever an exception occurs?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 12, 2021, 11:23

To remedy this, it would be nice to be able to see the number of outstanding messages (futures) in the Message Router... The same for the Threads...Are all the threads busy?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 19, 2021, 14:02

created merge request !110 to address this issue

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 22, 2021, 12:37

I've located the problem to the MessageRouter#unsetMessageDispatcher happening before a reply has been send and so the message dispatcher is `null` and it gives a `NullPointerException` which prevents the unregister function to be called.

What is a solid way to solve this? We can either force the unset method to be called when there are no outstanding messages, or we can check whether the message dispatcher is null before we call the send method of it.

Note that we cannot control _when_ Smart Connectors are shut down, so it can always happen that a SmartConnector is turned off in the middle of an exchange. How should we handle these types of situations?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 23, 2021, 12:55

short term solution:
- not null check in MessageRouter

long term solution (see #172):
- close a smart connector in 2 steps
- introduce an ErrorMessage
- use timeouts as proposed in #95 and others.
- @wilco.wijbrandi.tno.nl will do (part of) this in #43

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 23, 2021, 12:56

marked this issue as related to #172

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 23, 2021, 13:10

created merge request !120 to address this issue

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 23, 2021, 13:16

Another short term solution which is already used in other MessageRouter methods is to copy the messagedispatcher instance variable to a local variable and use that one for the entire method. Then setting the instance to null does not effect running methods.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 23, 2021, 13:32

mentioned in commit ba39b735586984f2b9030e6062751cd5cbf155a3
