### ISSUE TITLE
Increase the queue for outstanding handle requests.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#176]
In GitLab by @barry.nouwt.tno.nl on Apr 12, 2021, 10:20

Noticed the following exception in the LOG file of the Knowledge Engine on INESC TEC server.

```
2021-04-08 08:45:53:822 +0100 [pool-4-thread-4] WARN InteractionProcessorImpl-VLL Test - Encountered an unresolvable KnowledgeInteraction ID 'https://ke.interconnectproject.eu/adapter/97101794b6df73ed52fbb708fd9c066cc2e1487f31a1a147e7ab503c2decae52be20e584a927b47bdc01d8c3ba530b9406bf7e59dfa6a4e770a541c1cb417c49/interaction/81f9f06a-f9f2-42ab-9f0a-1913de903ec2' that was expected to resolve to one of our own.
java.lang.IllegalStateException: Queue full
	at java.base/java.util.AbstractQueue.add(AbstractQueue.java:98)
	at java.base/java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:326)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.toBeProcessedByKnowledgeBase(RestKnowledgeBase.java:171)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase$1.answer(RestKnowledgeBase.java:98)
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.InteractionProcessorImpl.processAskFromMessageRouter(InteractionProcessorImpl.java:128)
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.MessageRouterImpl.handleAskMessage(MessageRouterImpl.java:87)
	at eu.interconnectproject.knowledge_engine.smartconnector.runtime.JvmOnlyMessageDispatcher$SmartConnectorHandler.lambda$send$0(JvmOnlyMessageDispatcher.java:63)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
``` 

Looked at the eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.RestKnowledgeBase(SmartConnector) constructor at noticed that the size of the queue is 2 entries, which maybe is a bit low :).

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 16, 2021, 11:30

created merge request !106 to address this issue

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 16, 2021, 11:34

Increased the queue size to 50 simultaneous handle requests per knowledge base.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 16, 2021, 11:35

mentioned in commit bd52ca4fa96381bd10c85fd1bf5af9e57500d7cf
