### ISSUE TITLE
Can't start local KE

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#182]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 21, 2021, 14:12

Staring KE locally by following the instruction - README.md in the main branch, say to start the app by:

`java -Dorg.slf4j.simpleLogger.logFile=ke.log -cp "rest-api-0.1.0.jar:lib/*" eu.interconnectproject.knowledge_engine.rest.api.RestServer 8280`

The above command throws an error:

> knowledge-engine git:(master) ✗ java -Dorg.slf4j.simpleLogger.logFile=ke.log -cp "rest-api-0.1.0.jar:lib/*" eu.interconnectproject.knowledge_engine.rest.api.RestServer 8280
> Error: Could not find or load main class eu.interconnectproject.knowledge_engine.rest.api.RestServer
> Caused by: java.lang.ClassNotFoundException: eu.interconnectproject.knowledge_engine.rest.api.RestServer

Command `mvn dependency:copy-dependencies` also returns the errors:

> knowledge-engine git:(master) ✗ mvn dependency:copy-dependencies
> [INFO] Scanning for projects...
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Build Order:
> [INFO] 
> [INFO] Knowledge Engine                                                   [pom]
> [INFO] Knowledge Engine - Smart Connector                                 [jar]
> [INFO] Knowledge Engine - Admin UI                                        [jar]
> [INFO] Knowledge Engine - Examples                                        [jar]
> [INFO] Knowledge Engine - REST API                                        [jar]
> [INFO] 
> [INFO] ---------< eu.interconnectproject.knowledge_engine:ke-parent >----------
> [INFO] Building Knowledge Engine 0.1.1-SNAPSHOT                           [1/5]
> [INFO] --------------------------------[ pom ]---------------------------------
> [INFO] 
> [INFO] --- maven-dependency-plugin:2.8:copy-dependencies (default-cli) @ ke-parent ---
> [INFO] 
> [INFO] ------< eu.interconnectproject.knowledge_engine:smart-connector >-------
> [INFO] Building Knowledge Engine - Smart Connector 0.1.1-SNAPSHOT         [2/5]
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO] 
> [INFO] --- maven-dependency-plugin:2.8:copy-dependencies (default-cli) @ smart-connector ---
> [INFO] jackson-databind-2.12.1.jar already exists in destination.
> [INFO] commons-cli-1.4.jar already exists in destination.
> [INFO] jackson-annotations-2.12.1.jar already exists in destination.
> [INFO] jena-dboe-trans-data-4.0.0.jar already exists in destination.
> [INFO] libthrift-0.14.1.jar already exists in destination.
> [INFO] jena-dboe-index-4.0.0.jar already exists in destination.
> [INFO] jena-rdfconnection-4.0.0.jar already exists in destination.
> [INFO] httpclient-4.5.13.jar already exists in destination.
> [INFO] jena-shaded-guava-4.0.0.jar already exists in destination.
> [INFO] jgrapht-core-1.5.0.jar already exists in destination.
> [INFO] commons-lang3-3.11.jar already exists in destination.
> [INFO] jena-dboe-storage-4.0.0.jar already exists in destination.
> [INFO] collection-0.7.jar already exists in destination.
> [INFO] jena-core-4.0.0.jar already exists in destination.
> [INFO] jena-tdb2-4.0.0.jar already exists in destination.
> [INFO] jena-base-4.0.0.jar already exists in destination.
> [INFO] opentest4j-1.2.0.jar already exists in destination.
> [INFO] jena-iri-4.0.0.jar already exists in destination.
> [INFO] jena-dboe-transaction-4.0.0.jar already exists in destination.
> [INFO] junit-platform-commons-1.7.0.jar already exists in destination.
> [INFO] jsonld-java-0.13.2.jar already exists in destination.
> [INFO] apiguardian-api-1.1.0.jar already exists in destination.
> [INFO] jena-tdb-4.0.0.jar already exists in destination.
> [INFO] javax.annotation-api-1.3.2.jar already exists in destination.
> [INFO] jcl-over-slf4j-1.7.30.jar already exists in destination.
> [INFO] commons-codec-1.15.jar already exists in destination.
> [INFO] commons-io-2.8.0.jar already exists in destination.
> [INFO] junit-jupiter-engine-5.7.0.jar already exists in destination.
> [INFO] jena-arq-4.0.0.jar already exists in destination.
> [INFO] slf4j-simple-1.7.25.jar already exists in destination.
> [INFO] junit-jupiter-api-5.7.0.jar already exists in destination.
> [INFO] jackson-core-2.12.1.jar already exists in destination.
> [INFO] sspace-2.0.4.jar already exists in destination.
> [INFO] slf4j-api-1.7.25.jar already exists in destination.
> [INFO] jena-dboe-base-4.0.0.jar already exists in destination.
> [INFO] commons-csv-1.8.jar already exists in destination.
> [INFO] httpclient-cache-4.5.13.jar already exists in destination.
> [INFO] trove4j-3.0.3.jar already exists in destination.
> [INFO] junit-platform-engine-1.7.0.jar already exists in destination.
> [INFO] jena-shacl-4.0.0.jar already exists in destination.
> [INFO] commons-compress-1.20.jar already exists in destination.
> [INFO] httpcore-4.4.13.jar already exists in destination.
> [INFO] jheaps-0.13.jar already exists in destination.
> [INFO] apache-jena-libs-4.0.0.pom already exists in destination.
> [INFO] 
> [INFO] ----------< eu.interconnectproject.knowledge_engine:admin-ui >----------
> [INFO] Building Knowledge Engine - Admin UI 0.1.1-SNAPSHOT                [3/5]
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for Knowledge Engine 0.1.1-SNAPSHOT:
> [INFO] 
> [INFO] Knowledge Engine ................................... SUCCESS [  0.741 s]
> [INFO] Knowledge Engine - Smart Connector ................. SUCCESS [  0.248 s]
> [INFO] Knowledge Engine - Admin UI ........................ FAILURE [  0.029 s]
> [INFO] Knowledge Engine - Examples ........................ SKIPPED
> [INFO] Knowledge Engine - REST API ........................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  1.376 s
> [INFO] Finished at: 2021-04-21T16:07:09+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project admin-ui: Could not resolve dependencies for project eu.interconnectproject.knowledge_engine:admin-ui:jar:0.1.1-SNAPSHOT: Failure to find eu.interconnectproject.knowledge_engine:smart-connector:jar:0.1.1-SNAPSHOT in https://gitlab.inesctec.pt/api/v4/projects/2878/packages/maven was cached in the local repository, resolution will not be reattempted until the update interval of gitlab-maven has elapsed or updates are forced -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :admin-ui

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 21, 2021, 14:28

Additionally, it would help if i would be able to run the app in the IDE. I tried with the following run configuration:
- java 11
- module: rest-api
- main class: eu.interconnectproject.knowledge_engine.rest.api.RestServer

Throws this error:

> 2021-04-21 16:11:37:421 +0200 [main] INFO RestServer - Starting Knowledge Engine REST API on port 8280.
> Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletResponse
> 	at eu.interconnectproject.knowledge_engine.rest.api.RestServer.main(RestServer.java:29)
> Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletResponse
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 1 more
> 
> Process finished with exit code 1

Note that `mvn clean and package` commands were successful.  

I know this in not fully needed for os as early adopters, but would be nice to debug the issues that we have during development.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 14:28

If you checkout the ke-parent maven artifact (i.e. the root of the knowledge-engine repo) and use a popular Java IDE, you should be able to just run the RestServer.java class directly without problems.

We should double check the instructions in the readme.md and see what goes wrong here.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 14:29

Sorry, did not see your post yet.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 14:30

What IDE are you using?

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 21, 2021, 14:31

IntelliJ

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 14:31

Can it be that your IDE does not pick up the dependencies when running?

Because it cannot find the class: HttpServletResponse

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 21, 2021, 14:35

I think parent-ke is installed:

/Users/andraz/.m2/repository/eu/interconnectproject/knowledge_engine/ke-parent/0.1.0
➜  0.1.0 ls
ke-parent-0.1.0.jar.lastUpdated ke-parent-0.1.0.pom.lastUpdated

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 21, 2021, 14:37

Running it manually:

> knowledge-engine git:(master) ✗ mvn dependency:get -Dartifact=eu.interconnectproject.knowledge_engine:ke-parent:0.1.0
> [INFO] Scanning for projects...
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Build Order:
> [INFO] 
> [INFO] Knowledge Engine                                                   [pom]
> [INFO] Knowledge Engine - Smart Connector                                 [jar]
> [INFO] Knowledge Engine - Admin UI                                        [jar]
> [INFO] Knowledge Engine - Examples                                        [jar]
> [INFO] Knowledge Engine - REST API                                        [jar]
> [INFO] 
> [INFO] ---------< eu.interconnectproject.knowledge_engine:ke-parent >----------
> [INFO] Building Knowledge Engine 0.1.1-SNAPSHOT                           [1/5]
> [INFO] --------------------------------[ pom ]---------------------------------
> [INFO] 
> [INFO] --- maven-dependency-plugin:2.8:get (default-cli) @ ke-parent ---
> [INFO] Resolving eu.interconnectproject.knowledge_engine:ke-parent:jar:0.1.0 with transitive dependencies
> [WARNING] Missing POM for eu.interconnectproject.knowledge_engine:ke-parent:jar:0.1.0
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for Knowledge Engine 0.1.1-SNAPSHOT:
> [INFO] 
> [INFO] Knowledge Engine ................................... FAILURE [  0.637 s]
> [INFO] Knowledge Engine - Smart Connector ................. SKIPPED
> [INFO] Knowledge Engine - Admin UI ........................ SKIPPED
> [INFO] Knowledge Engine - Examples ........................ SKIPPED
> [INFO] Knowledge Engine - REST API ........................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  0.965 s
> [INFO] Finished at: 2021-04-21T16:36:36+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:get (default-cli) on project ke-parent: Couldn't download artifact: Missing:
> [ERROR] ----------
> [ERROR] 1) eu.interconnectproject.knowledge_engine:ke-parent:jar:0.1.0
> [ERROR] 
> [ERROR]   Try downloading the file manually from the project website.
> [ERROR] 
> [ERROR]   Then, install it using the command: 
> [ERROR]       mvn install:install-file -DgroupId=eu.interconnectproject.knowledge_engine -DartifactId=ke-parent -Dversion=0.1.0 -Dpackaging=jar -Dfile=/path/to/file
> [ERROR] 
> [ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
> [ERROR]       mvn deploy:deploy-file -DgroupId=eu.interconnectproject.knowledge_engine -DartifactId=ke-parent -Dversion=0.1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
> [ERROR] 
> [ERROR]   Path to dependency: 
> [ERROR]         1) org.apache.maven.plugins:maven-downloader-plugin:jar:1.0
> [ERROR]         2) eu.interconnectproject.knowledge_engine:ke-parent:jar:0.1.0
> [ERROR] 
> [ERROR] ----------
> [ERROR] 1 required artifact is missing.
> [ERROR] 
> [ERROR] for artifact: 
> [ERROR]   org.apache.maven.plugins:maven-downloader-plugin:jar:1.0
> [ERROR] 
> [ERROR] from the specified remote repositories:
> [ERROR]   gitlab-maven (https://gitlab.inesctec.pt/api/v4/projects/2878/packages/maven, releases=true, snapshots=true),
> [ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
> [ERROR] 
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


Might be something with the credentials?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 14:40

No credentials necessary...so I would not expect that to be the problem.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 14:41

Do you have other Maven project in your IntelliJ in which dependencies get picked up correctly?

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 21, 2021, 14:51

Yes, i have but the issue i think is here:

[ERROR] 1 required artifact is missing.
[ERROR] 
[ERROR] for artifact: 
[ERROR]   org.apache.maven.plugins:maven-downloader-plugin:jar:1.0
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   gitlab-maven (https://gitlab.inesctec.pt/api/v4/projects/2878/packages/maven, releases=true, snapshots=true),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Apr 21, 2021, 14:59

For the issue with dependencies, can you try the following?

```bash
mvn clean install -DskipTests
mvn dependency:copy-dependencies
```

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 15:01

Aaah...yes, that indeed is a problem. Although it would not need that repo if you `mvn clean install` everything successfully, I think.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 15:19

Did you checkout the master or the 0.1.0 tag?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 15:21

The README.md is a bit misleading, because the instructions were written for a python-example.zip that we provided before the repo was up.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 15:27

@andraz.andolsek.cyber-grid.com Can you check if there is a pom.xml in this folder: `/Users/andraz/.m2/repository/eu/interconnectproject/knowledge_engine/ke-parent/0.1.0`

If you checkout the `0.1.0` tag of the `ke-parent` and you run `mvn clean install` from the root of that repository, can you post the maven log? Or is that the log you posted above?

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 21, 2021, 17:51

this is in the 0.1.0 folder

> -rw-r--r--  1 andraz  staff   252B Apr 21 19:38 ke-parent-0.1.0.pom.lastUpdated
> ➜  0.1.0 car ke-parent-0.1.0.pom.lastUpdated 
> zsh: command not found: car
> ➜  0.1.0 cat ke-parent-0.1.0.pom.lastUpdated 
> #NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
> #Wed Apr 21 19:38:41 CEST 2021
> https\://repo.maven.apache.org/maven2/.lastUpdated=1619026721889
> https\://repo.maven.apache.org/maven2/.error=
> ➜  0.1.0 

By checkout you mean set the version to 0.1.0 instead of 0.1.1-SNAPHOST in the rest-api pom.xml of ke-parent? If so here is the output:

> ➜  knowledge-engine git:(master) ✗ mvn clean install
> [INFO] Scanning for projects...
> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [FATAL] Non-resolvable parent POM for eu.interconnectproject.knowledge_engine:rest-api:0.1.0: Failure to find eu.interconnectproject.knowledge_engine:ke-parent:pom:0.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 7, column 10
>  @ 
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]   
> [ERROR]   The project eu.interconnectproject.knowledge_engine:rest-api:0.1.0 (/Users/andraz/Development/interconnect/knowledge-engine/rest-api/pom.xml) has 1 error
> [ERROR]     Non-resolvable parent POM for eu.interconnectproject.knowledge_engine:rest-api:0.1.0: Failure to find eu.interconnectproject.knowledge_engine:ke-parent:pom:0.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 7, column 10 -> [Help 2]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 21, 2021, 17:52

It looks like it still wants to go to the repo.maven.apache.org to fetch the ke-parent. 
FYI: I removed all local settings of the other repository links.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 21, 2021, 18:29

By checkout I mean doing a `git checkout 0.1.0` command and then the `mvn clean install` from the root. You should not have to change the versions in pom.xml.

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 22, 2021, 05:52

I don’t have access to the ke-parent project.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 22, 2021, 06:22

That's strange, because you have developer access rights to this repository. You should be able to clone this repository and run the `mvn clean install` from the root of the repo.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 22, 2021, 06:24

BTW the [`pom.xml`](https://gitlab.inesctec.pt/interconnect/knowledge-engine/-/blob/0.1.0/pom.xml#L7) in the root of this repo _is_ that of the `ke-parent`.

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 22, 2021, 06:43

Sorry, my bad i automatically assumed this is the separate project. I checkout tag 0.1.0 do the mvn clean install, run the mvn dependency:copy-dependencies and trigger:

 java -Dorg.slf4j.simpleLogger.logFile=ke.log -cp "rest-api-0.1.0.jar:lib/*" eu.interconnectproject.knowledge_engine.rest.api.RestServer 8280

i get this output:

Error: Could not find or load main class eu.interconnectproject.knowledge_engine.rest.api.RestServer
Caused by: java.lang.ClassNotFoundException: eu.interconnectproject.knowledge_engine.rest.api.RestServer

My local repo show the following for the ke-parent:

> ➜  0.1.0 pwd
> /Users/andraz/.m2/repository/eu/interconnectproject/knowledge_engine/ke-parent/0.1.0
> ➜  0.1.0 ls -ltr
> total 16
> -rw-r--r--  1 andraz  staff  1496 Apr 22 08:36 ke-parent-0.1.0.pom
> -rw-r--r--  1 andraz  staff   163 Apr 22 08:37 _remote.repositories
> ➜  0.1.0

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 22, 2021, 06:48

Thanks for the effort, Andraz. 

The instructions in the readme.md are not correct, sorry about that.

Did the `mvn clean install` complete succesfully?

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 22, 2021, 06:51

No worries, yes it completed successfully.

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 22, 2021, 07:01

I have solved the issue. This needs to be replaces with the following steps:
- move to the rest-api/target
- run the command:

`java -Dorg.slf4j.simpleLogger.logFile=ke.log -cp "rest-api-0.1.0.jar:dependency/*" eu.interconnectproject.knowledge_engine.rest.api.RestServer 8280`

Note: i replaced folder lib with the dependency.
I will not try same with master branch.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 22, 2021, 07:02

Ok, that's good news. So, now your local Maven repository contains the required 0.1.0 jar-files.

Now we should focus on how to configure a Maven project correctly in IntelliJ. I always use Eclipse, but IntelliJ should also work.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 22, 2021, 07:04

I am looking at this [website](https://www.jetbrains.com/help/idea/maven-support.html#maven_multi_module)

Do you also have a Maven tool where you can check if the dependencies of the rest-api project have smart-connector 0.1.0 in there?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 22, 2021, 07:13

Sorry, missed your post again. Now you at least can easily restart the local server if it is in an illegal state.

It should also be possible to run RestServer.java from within your IDE, so let me know if/when you want to get that to work.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 22, 2021, 07:21

created merge request !114 to address this issue

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 22, 2021, 07:28

mentioned in commit 0676fa3ca0ef2bb6aad7ebe8ed64e1b987d97dc6

**Comment by Sophietje** [comment]
In GitLab by @andraz.andolsek.cyber-grid.com on Apr 22, 2021, 07:29

For now it is ok, to run via cmd, but in future this might be helpful. From what i can see is that IntelliJ can't match the dependencies with this configuration. 
Usually we work with multi-module projects without a problem (but using Spring boot).

FYI the master branch also works.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 22, 2021, 07:30

I have updated the documentation to make it more clear how to run a local instance of the Rest API Server. Closed this issue for now.
