### ISSUE TITLE
Also validate whether the incoming parameters of the different API methods are non-null.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#187]
In GitLab by @barry.nouwt.tno.nl on Apr 26, 2021, 06:44

Null pointer exception because there is no JSON given. Maybe also check whether using the 'required' property of OpenAPI would prevent this?

```
2021-04-24 08:04:10:864 +0100 [qtp1450821318-971] WARN HttpChannel - /rest/sc/handle
javax.servlet.ServletException: java.lang.NullPointerException
at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:497)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
at eu.interconnectproject.knowledge_engine.rest.api.impl.ReactiveApiServiceImpl.scHandlePost(ReactiveApiServiceImpl.java:151)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
... 18 more
2021-04-24 08:04:10:866 +0100 [qtp1450821318-971] WARN HttpChannel - Could not send response error 500: javax.servlet.ServletException: java.lang.NullPointerException
```

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 26, 2021, 07:42

I see some of the requestBody parameters in the OpenAPI REST API spec have the `required` property, but some also do not. Does this property actually do something?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 26, 2021, 07:53

There are annotation like required or notnull on the different methods in the generated code, but somehow these do work.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 26, 2021, 07:57

Maybe this is caused by:
- https://stackoverflow.com/questions/35854304/notnull-annotation-not-working-as-expected-java-jersey

There is no `bean-validation` dependency on the rest-api artifact. There is a `validation-api` dependency though, is it the new one?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 26, 2021, 08:11

Unfortunately, when setting validation-api to `compile` instaed of `provided` it does not work also adding `bean-validation` dependencies fails with class or method not found exceptions.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 26, 2021, 12:22

created merge request !124 to address this issue

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 30, 2021, 12:48

mentioned in commit ce4f1f7805fa736b1d857a15a71ae6d2b04399c6
