### ISSUE TITLE
Repeating NullPointerException in log of cloud KE.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#210]
In GitLab by @barry.nouwt.tno.nl on May 20, 2021, 15:19

```
2021-05-17 10:23:40:052 +0100 [pool-3-thread-1] DEBUG MessageRouterImpl-OMTest ASK - Sent AskMessage: AskMessage [getToKnowledgeBase()=https://ke.interconnectproject.eu/adapter/660075654c6971dfc811399e682fead8f93a705ecc3c1168d9e8d471ab587335ce49be1efc51180edbb58a177d12be10bf0a8099d51060f12dbcd5eed59ea0c8, getToKnowledgeInteraction()=https://ke.interconnectproject.eu/adapter/660075654c6971dfc811399e682fead8f93a705ecc3c1168d9e8d471ab587335ce49be1efc51180edbb58a177d12be10bf0a8099d51060f12dbcd5eed59ea0c8/interaction/98dbde73-39d2-4f64-8d56-ce8db10b3f94, getFromKnowledgeBase()=https://ke.interconnectproject.eu/adapter/d8f7c4207e0b7c604255097ad522bfccef629806fec00f15f944d825326b41b6137fd2c2772a90af1a511b3033d48d75a9a53b60eeabd1dc079efb6e7bb7b0fa, getFromKnowledgeInteraction()=https://ke.interconnectproject.eu/adapter/d8f7c4207e0b7c604255097ad522bfccef629806fec00f15f944d825326b41b6137fd2c2772a90af1a511b3033d48d75a9a53b60eeabd1dc079efb6e7bb7b0fa/interaction/24fffe94-2f41-40d4-a811-501167da6581, getMessageId()=8528cba7-b890-434e-b9a2-26d413cd63b1, getBindings()=[Binding [map={p=<http://www.tno.nl/p1>, s=<http://www.tno.nl/s1>, o=<http://www.tno.nl/o1>}]]]
2021-05-17 10:23:40:053 +0100 [pool-3-thread-1] DEBUG MessageRouterImpl-OMTest ASK - Received AnswerMessage: AnswerMessage [getToKnowledgeBase()=https://ke.interconnectproject.eu/adapter/d8f7c4207e0b7c604255097ad522bfccef629806fec00f15f944d825326b41b6137fd2c2772a90af1a511b3033d48d75a9a53b60eeabd1dc079efb6e7bb7b0fa, getToKnowledgeInteraction()=https://ke.interconnectproject.eu/adapter/d8f7c4207e0b7c604255097ad522bfccef629806fec00f15f944d825326b41b6137fd2c2772a90af1a511b3033d48d75a9a53b60eeabd1dc079efb6e7bb7b0fa/interaction/24fffe94-2f41-40d4-a811-501167da6581, getFromKnowledgeBase()=https://ke.interconnectproject.eu/adapter/6ba941447b848c572292e6f9cd4e2e404f9c611085998c0389fe66cfe93301eb9ffcb9acd2b82183b7432ddd1f19fd4efe92829392dac7ce3bf138b4c55cccbf, getFromKnowledgeInteraction()=https://ke.interconnectproject.eu/adapter/6ba941447b848c572292e6f9cd4e2e404f9c611085998c0389fe66cfe93301eb9ffcb9acd2b82183b7432ddd1f19fd4efe92829392dac7ce3bf138b4c55cccbf/interaction/ce90b05a-b7d4-4e93-9934-c0d77ec8a0e8, getMessageId()=c98d1a11-4176-4e6e-9142-4e58cda9defa, getReplyToAskMessage()=753cc977-119e-4e1e-98e9-e6529c1fd787, getBindings()=[Binding [map={p=<http://www.tno.nl/p1>, s=<http://www.tno.nl/s1>, o=<http://www.tno.nl/o1>}]]]
2021-05-17 10:23:40:053 +0100 [pool-6-thread-1] ERROR JvmOnlyMessageDispatcher - No errors should occur.
java.lang.NullPointerException
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.MetaKnowledgeBaseImpl.isMetaKnowledgeInteraction(MetaKnowledgeBaseImpl.java:558)
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.MessageRouterImpl.handleAskMessage(MessageRouterImpl.java:79)
	at eu.interconnectproject.knowledge_engine.smartconnector.runtime.JvmOnlyMessageDispatcher$SmartConnectorHandler.lambda$send$0(JvmOnlyMessageDispatcher.java:63)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on May 28, 2021, 08:04

Seems to have been solved in the log of version 0.1.7 (been running for a week).
