### ISSUE TITLE
Unparseable graph patterns should not give a 500 message but a 400 with explanation.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#217]
In GitLab by @barry.nouwt.tno.nl on May 25, 2021, 15:45

Currently, the log of the KE is full of the exceptions below. Make sure we handle graph pattern parse exceptions correctly and return a useful message to the user.

``` 
2021-05-25 17:43:08:412 +0200 [qtp1348949648-23] INFO ReactiveApiServiceImpl - scKiPost called: class ReactKnowledgeInteraction {
    class KnowledgeInteractionBase {
        knowledgeInteractionType: ReactKnowledgeInteraction
        communicativeAct: null
    }
    argumentGraphPattern: ?s saref:hasMeasurement ?o
    resultGraphPattern: ?a ?b ?c
}
2021-05-25 17:43:08:421 +0200 [qtp1348949648-23] WARN ServletHandler - 
javax.servlet.ServletException: org.apache.jena.query.QueryParseException: Line 1, column 4: Unresolved prefixed name: saref:hasMeasurement
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.jena.query.QueryParseException: Line 1, column 4: Unresolved prefixed name: saref:hasMeasurement
	at org.apache.jena.sparql.lang.QueryParserBase.throwParseException(QueryParserBase.java:578)
	at org.apache.jena.sparql.lang.QueryParserBase.resolvePName(QueryParserBase.java:320)
	at org.apache.jena.sparql.lang.arq.ARQParser.PrefixedName(ARQParser.java:6316)
	at org.apache.jena.sparql.lang.arq.ARQParser.iri(ARQParser.java:6300)
	at org.apache.jena.sparql.lang.arq.ARQParser.PathPrimary(ARQParser.java:3723)
	at org.apache.jena.sparql.lang.arq.ARQParser.PathElt(ARQParser.java:3582)
	at org.apache.jena.sparql.lang.arq.ARQParser.PathEltOrInverse(ARQParser.java:3610)
	at org.apache.jena.sparql.lang.arq.ARQParser.PathSequence(ARQParser.java:3545)
	at org.apache.jena.sparql.lang.arq.ARQParser.PathAlternative(ARQParser.java:3524)
	at org.apache.jena.sparql.lang.arq.ARQParser.Path(ARQParser.java:3518)
	at org.apache.jena.sparql.lang.arq.ARQParser.VerbPath(ARQParser.java:3473)
	at org.apache.jena.sparql.lang.arq.ARQParser.PropertyListPathNotEmpty(ARQParser.java:3398)
	at org.apache.jena.sparql.lang.arq.ARQParser.TriplesSameSubjectPath(ARQParser.java:3345)
	at org.apache.jena.sparql.lang.arq.ARQParser.TriplesBlock(ARQParser.java:2494)
	at org.apache.jena.sparql.lang.arq.ARQParser.GroupGraphPatternSub(ARQParser.java:2407)
	at eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.parseGraphPattern(GraphPattern.java:127)
	at eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.<init>(GraphPattern.java:61)
	at eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.<init>(GraphPattern.java:80)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.register(RestKnowledgeBase.java:279)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.KnowledgeInteractionLifeCycleApiServiceImpl.scKiPost(KnowledgeInteractionLifeCycleApiServiceImpl.java:48)
	at eu.interconnectproject.knowledge_engine.rest.api.KnowledgeInteractionLifeCycleApi.scKiPost(KnowledgeInteractionLifeCycleApi.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	... 18 more
2021-05-25 17:43:08:423 +0200 [qtp1348949648-23] WARN HttpChannel - /rest/sc/ki
javax.servlet.ServletException: org.apache.jena.query.QueryParseException: Line 1, column 4: Unresolved prefixed name: saref:hasMeasurement
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.jena.query.QueryParseException: Line 1, column 4: Unresolved prefixed name: saref:hasMeasurement
	at org.apache.jena.sparql.lang.QueryParserBase.throwParseException(QueryParserBase.java:578)
	at org.apache.jena.sparql.lang.QueryParserBase.resolvePName(QueryParserBase.java:320)
	at org.apache.jena.sparql.lang.arq.ARQParser.PrefixedName(ARQParser.java:6316)
	at org.apache.jena.sparql.lang.arq.ARQParser.iri(ARQParser.java:6300)
	at org.apache.jena.sparql.lang.arq.ARQParser.PathPrimary(ARQParser.java:3723)
	at org.apache.jena.sparql.lang.arq.ARQParser.PathElt(ARQParser.java:3582)
	at org.apache.jena.sparql.lang.arq.ARQParser.PathEltOrInverse(ARQParser.java:3610)
	at org.apache.jena.sparql.lang.arq.ARQParser.PathSequence(ARQParser.java:3545)
	at org.apache.jena.sparql.lang.arq.ARQParser.PathAlternative(ARQParser.java:3524)
	at org.apache.jena.sparql.lang.arq.ARQParser.Path(ARQParser.java:3518)
	at org.apache.jena.sparql.lang.arq.ARQParser.VerbPath(ARQParser.java:3473)
	at org.apache.jena.sparql.lang.arq.ARQParser.PropertyListPathNotEmpty(ARQParser.java:3398)
	at org.apache.jena.sparql.lang.arq.ARQParser.TriplesSameSubjectPath(ARQParser.java:3345)
	at org.apache.jena.sparql.lang.arq.ARQParser.TriplesBlock(ARQParser.java:2494)
	at org.apache.jena.sparql.lang.arq.ARQParser.GroupGraphPatternSub(ARQParser.java:2407)
	at eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.parseGraphPattern(GraphPattern.java:127)
	at eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.<init>(GraphPattern.java:61)
	at eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.<init>(GraphPattern.java:80)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.register(RestKnowledgeBase.java:279)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.KnowledgeInteractionLifeCycleApiServiceImpl.scKiPost(KnowledgeInteractionLifeCycleApiServiceImpl.java:48)
	at eu.interconnectproject.knowledge_engine.rest.api.KnowledgeInteractionLifeCycleApi.scKiPost(KnowledgeInteractionLifeCycleApi.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	... 18 more
2021-05-25 17:43:08:424 +0200 [qtp1348949648-23] WARN HttpChannel - Could not send response error 500: javax.servlet.ServletException: org.apache.jena.query.QueryParseException: Line 1, column 4: Unresolved prefixed name: saref:hasMeasurement
```

This is caused by using prefixes, which are not yet supported:

```
{
    class KnowledgeInteractionBase {
        knowledgeInteractionType: ReactKnowledgeInteraction
        communicativeAct: null
    }
    argumentGraphPattern: ?s saref:hasMeasurement ?o
    resultGraphPattern: ?a ?b ?c
}
```

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on May 28, 2021, 12:39

created merge request !158 to address this issue

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on May 28, 2021, 12:49

mentioned in commit b96c2721ae72c6e317aac9e3cf1bb31b48f56525
