### ISSUE TITLE
Problem accessing /rest/sc/ki. Request Failed

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#218]
In GitLab by @johan.kumps.realdolmen.com on May 26, 2021, 12:25

Hello,

I'm trying to setup a scenario using a post/react KI based on the testing code and examples in the KE Gitlab project:

```
var client = new RestApiClient("https://ke.interconnectproject.eu/rest");
		PrefixMappingMem prefixes = new PrefixMappingMem();
		prefixes.setNsPrefixes(PrefixMapping.Standard);
		prefixes.setNsPrefix("sosa", "http://www.w3.org/ns/sosa/");
		prefixes.setNsPrefix("ic", "https://www.tno.nl/energy/ontology/interconnect/");
		prefixes.setNsPrefix("ex", "https://www.tno.nl/example/");

		// Post a new SC with a POST KI.
		client.postSc(KB_ID, "A knowledge base", "A very descriptive piece of text.");

		// then register the relevant knowledge interactions
		GraphPattern obsGraphPattern = new GraphPattern(prefixes,
				"?d rdf:type saref4ener:Device . \n" + "?d saref:makesMeasurement ?m . \n" + "?m saref:relatesToProperty ?p . \n"
				+ "?p rdf:type saref4ener:Power . \n"+ "?m saref:hasTimestamp ?ts . \n" + "?m saref:hasValue ?pwr .");
		PostKnowledgeInteraction smartMeterPostKnowledgeInteraction = new PostKnowledgeInteraction(new CommunicativeAct(), obsGraphPattern, null);

		String ki1 = client.postKiPost(KB_ID, smartMeterPostKnowledgeInteraction.getArgument().getPattern(), null);
```

The client.postKiPost call seems to fail. A HTML message is returned and stored in the ki1 string. This is the console output:

```
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2021-05-26 14:19:19:269 +0200 [main] INFO PostingClient - Made new KI with ID <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /rest/sc/ki. Reason:
<pre>    Request failed.</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

2021-05-26 14:19:20:280 +0200 [main] INFO PostingClient - Sending POST: [Binding [map={obs=<https://www.tno.nl/example/obs1>, temp=23, id=<https://www.tno.nl/example/room1>, room="room1"}]]`
```
What can be wrong?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 27, 2021, 07:12

Hi @johan.kumps.realdolmen.com, 

this is probably incorrect validation behavior. I noticed that you are registering a Post Knowledge Interaction with a graph pattern:

```
?d rdf:type saref4ener:Device . 
?d saref:makesMeasurement ?m . 
?m saref:relatesToProperty ?p .
?p rdf:type saref4ener:Power . 
?m saref:hasTimestamp ?ts .
?m saref:hasValue ?pwr .
```

where you use prefixes like rdf, saref and saref4ener. Currently, the Knowledge Engine does not support prefixes in Graph Patterns (in the REST API) and for simplicity reasons, just define your graph pattern as a String.

Try changing your code to something like this:

```
		var client = new RestApiClient("https://ke.interconnectproject.eu/rest");
		// Post a new SC with a POST KI.
		client.postSc(KB_ID, "A knowledge base", "A very descriptive piece of text.");

		// then register the relevant knowledge interactions
		String graphPattern = "?d <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://saref.etsi.org/saref4ener/Device> . "
				+ "?d <https://saref.etsi.org/core/makesMeasurement> ?m . "
				+ "?m <https://saref.etsi.org/core/relatesToProperty> ?p . "
				+ "?p <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://saref.etsi.org/saref4ener/Power> . "
				+ "?m <https://saref.etsi.org/core/hasTimestamp> ?ts ."
				+ "?m <https://saref.etsi.org/core/hasValue> ?pwr .";

		String ki1 = client.postKiPost(KB_ID, graphPattern, null);
```

Does this give better results? Regarding the status 500 code, I already created #203 to improve the validation.

Hope you can get it working!

Regards, Barry

**Comment by Sophietje** [comment]
In GitLab by @johan.kumps.realdolmen.com on May 27, 2021, 09:13

When trying the code with al KE instance running locally it actually runs fine. What I noticed is that the resultPattern is not optional. I thought it was for the Post/React paradigm?

The changed (having a resultPattern) still gives the same issue when I use the KE in the cloud.

**Comment by Sophietje** [comment]
In GitLab by @johan.kumps.realdolmen.com on May 27, 2021, 14:41

When I leave the result pattern null:

```
String ki1 = client.postKiPost(KB_ID, smartMeterPostKnowledgeInteraction.getArgument().getPattern(),
				//"?d ?e ?f.");
				null);
```

I can see this in the KE logs :

```
2021-05-27 16:37:19:065 +0200 [qtp466002798-22] INFO ReactiveApiServiceImpl - scHandleGet() called!
2021-05-27 16:37:28:603 +0200 [qtp466002798-23] INFO ReactiveApiServiceImpl - scKiPost called: class KnowledgeInteraction {
    knowledgeInteractionType: PostKnowledgeInteraction
    communicativeAct: null
    graphPattern: null
    argumentGraphPattern: ?d <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://saref.etsi.org/saref4ener/Device> . ?d <https://saref.etsi.org/core/makesMeasurement> ?m . ?m <https://saref.etsi.org/core/relatesToProperty> ?p . ?p <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://saref.etsi.org/saref4ener/Power> . ?m <https://saref.etsi.org/core/hasTimestamp> ?ts .?m <https://saref.etsi.org/core/hasValue> ?pwr .
    resultGraphPattern: null
}
2021-05-27 16:37:28:631 +0200 [qtp466002798-23] INFO SmartConnectorImpl-A knowledge base - Registered Post KI <https://www.interconnectproject.eu/knowledge-engine/knowledgebase/example/a-measurements-posting-kb-6c465658-28d9-420e-9730-2bea8fe6bb06/interaction/1d2badf3-5f5b-49f3-9bb0-1ada16c35d00>.
2021-05-27 16:37:28:815 +0200 [pool-6-thread-1] INFO SmartConnectorImpl-A knowledge base - Ready to exchange data.
2021-05-27 16:37:29:675 +0200 [qtp466002798-22] WARN ServletHandler - 
javax.servlet.ServletException: java.lang.NullPointerException: Cannot invoke "eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.getPattern()" because the return value of "eu.interconnectproject.knowledge_engine.smartconnector.api.PostKnowledgeInteraction.getResult()" is null
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Cannot invoke "eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.getPattern()" because the return value of "eu.interconnectproject.knowledge_engine.smartconnector.api.PostKnowledgeInteraction.getResult()" is null
	at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.kiToModelKiWithId(RestKnowledgeBase.java:346)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.getKnowledgeInteraction(RestKnowledgeBase.java:314)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.ProactiveApiServiceImpl.scPostPost(ProactiveApiServiceImpl.java:82)
	at eu.interconnectproject.knowledge_engine.rest.api.ProactiveApi.scPostPost(ProactiveApi.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	... 18 more
2021-05-27 16:37:29:677 +0200 [qtp466002798-22] WARN HttpChannel - /rest/sc/post
javax.servlet.ServletException: java.lang.NullPointerException: Cannot invoke "eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.getPattern()" because the return value of "eu.interconnectproject.knowledge_engine.smartconnector.api.PostKnowledgeInteraction.getResult()" is null
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Cannot invoke "eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.getPattern()" because the return value of "eu.interconnectproject.knowledge_engine.smartconnector.api.PostKnowledgeInteraction.getResult()" is null
	at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.kiToModelKiWithId(RestKnowledgeBase.java:346)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.getKnowledgeInteraction(RestKnowledgeBase.java:314)
	at eu.interconnectproject.knowledge_engine.rest.api.impl.ProactiveApiServiceImpl.scPostPost(ProactiveApiServiceImpl.java:82)
	at eu.interconnectproject.knowledge_engine.rest.api.ProactiveApi.scPostPost(ProactiveApi.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	... 18 more
2021-05-27 16:37:29:679 +0200 [qtp466002798-22] WARN HttpChannel - Could not send response error 500: javax.servlet.ServletException: java.lang.NullPointerException: Cannot invoke "eu.interconnectproject.knowledge_engine.smartconnector.api.GraphPattern.getPattern()" because the return value of "eu.interconnectproject.knowledge_engine.smartconnector.api.PostKnowledgeInteraction.getResult()" is null
2021-05-27 16:37:48:073 +0200 [jersey-background-task-scheduler-0] INFO ReactiveApiServiceImpl - handleTimeout called!
```

The log of the PostingClient :

```
2021-05-27 16:37:28:636 +0200 [main] INFO PostingClient - Made new KI with ID https://www.interconnectproject.eu/knowledge-engine/knowledgebase/example/a-measurements-posting-kb-6c465658-28d9-420e-9730-2bea8fe6bb06/interaction/1d2badf3-5f5b-49f3-9bb0-1ada16c35d00
2021-05-27 16:37:29:654 +0200 [main] INFO PostingClient - Sending POST: [Binding [map={p=<https://www.tno.nl/example/prop1>, d=<https://www.tno.nl/example/device1>, pwr=10, m=<https://www.tno.nl/example/meas1>, ts='2002-0530T09:00:00^^xsd:timestamp'}]]
--> Response{protocol=http/1.1, code=500, message=Request failed., url=http://localhost:8280/rest/sc/post}
Exception in thread "main" java.lang.RuntimeException: Failed request. Message: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /rest/sc/post. Reason:
<pre>    Request failed.</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

	at eu.interconnectproject.knowledge_engine.rest.api.client_example.RestApiClient.postPost(RestApiClient.java:272)
	at eu.interconnectproject.knowledge_engine.rest.api.client_example.measurements_post_react.PostingClient.main(PostingClient.java:88)

Process finished with exit code 1
```

Could you indicate where the fix should be made? This way I can check whether I have this fix locally.

Johan,

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 27, 2021, 15:09

Are you sure you are using the latest local version of the RestServer? In the `master` branch the NullPointerException seems to be prevented with a `getResult() != null` check.

**Comment by Sophietje** [comment]
In GitLab by @johan.kumps.realdolmen.com on May 27, 2021, 19:27

@barry.nouwt.tno.nl  In which class this check should be present?

In the SerialMatchingProcessor class line 147 does this check. Is this the one you mean?

`if (pKI.getResult() != null) `

In case it is, I'm afraid this does not fully fix the issue.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 28, 2021, 06:29

The exception above happens in the `RestKnowledgeBase.java` class of the `rest-api` module. I meant this particular line: https://gitlab.inesctec.pt/interconnect/knowledge-engine/-/blob/master/rest-api/src/main/java/eu/interconnectproject/knowledge_engine/rest/api/impl/RestKnowledgeBase.java#L349

Does your local version have a `getResult() != null` check there? You can also just `git pull` and see if new changes are available.

**Comment by Sophietje** [comment]
In GitLab by @johan.kumps.realdolmen.com on May 28, 2021, 08:18

I did not have this fix locally deployed. The resultPattern can be null now. Thanks!

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 28, 2021, 08:36

Good to hear this solves it!

I am closing this issue now. Feel free to reopen it or create a new one if necessary.
