### ISSUE TITLE
POST /sc/ki always returns 500 (Can't register knowledge interactions)

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#272]
In GitLab by @jarne.kerkaert.inetum-realdolmen.world on Aug 9, 2021, 11:50

Since today, the `/sc/ki` endpoint returns 500, not matter which graph pattern I use. Our deployed services have also stopped working because of this.

The problem does not appear on a local instance.

Here is the full request:

```
POST /rest/sc/ki HTTP/1.1
Knowledge-Base-Id: http://interconnect.eu/partner
Content-Type: application/json; charset=UTF-8
User-Agent: PostmanRuntime/7.28.2
Accept: */*
Cache-Control: no-cache
Postman-Token: b34bcbd4-32d4-4cf8-8099-31faa939abce
Host: ke.interconnectproject.eu
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 144
 
{
"knowledgeInteractionType": "PostKnowledgeInteraction",
"argumentGraphPattern": "?s <sdf:sdfsdf> ?o",
"resultGraphPattern": null
}
 
HTTP/1.1 500 Internal Server Error
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 294
Content-Type: text/html; charset=ISO-8859-1
Date: Mon, 09 Aug 2021 11:42:24 GMT
Server: Caddy
Server: Jetty(9.2.9.v20150224)
 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /rest/sc/ki. Reason:
<pre> Request failed.</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Aug 9, 2021, 12:27

Thanks, I'll see if I can find something in the logs!

We were planning to do a new release this week, so that might also solve some issues.

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Aug 9, 2021, 12:40

This state seems to have been triggered this morning because of an invalid IRI (note the 4 forward slashes following `https:`):

```
2021-08-09 09:13:42:997 +0100 [pool-15-thread-1] ERROR SPARQL - [line: 1, col: 13] Bad IRI: 'https:////ke.interconnectproject.eu/adapter/d1492e767e72c22826538f420807ceabc1803eb46260816efa0483dc7a359e4b5e1fc1bae9d1b607d6f89d408a7ae76700808b1362ffcb4a8b90c0098e30187d/meta/knowledgeinteractions/post/new/act/requirement': <https:////ke.interconnectproject.eu/adapter/d1492e767e72c22826538f420807ceabc1803eb46260816efa0483dc7a359e4b5e1fc1bae9d1b607d6f89d408a7ae76700808b1362ffcb4a8b90c0098e30187d/meta/knowledgeinteractions/post/new/act/requirement> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
```

Seeing the IRI, it seems to be coming from the generic adapter

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Aug 9, 2021, 12:46

I could reproduce this locally (on the latest `master`) by using a KB ID with four forward slashes:

<details><summary>Click to expand logs</summary>



```
2021-08-09 12:43:34:515 +0000 [main] INFO RestServer - Starting Knowledge Engine REST API on port 8280.
2021-08-09 12:43:53:238 +0000 [qtp1752203484-16] INFO RestKnowledgeBaseManager - RestKnowledgeBaseManager initialized!
2021-08-09 12:43:54:112 +0000 [qtp1752203484-16] WARN KeRuntime - No configuration provided for Knowledge Directory, starting Knowledge Engine in local mode
2021-08-09 12:43:54:545 +0000 [qtp1752203484-16] INFO MessageDispatcher - Notifying 1 listeners about the 1 knowledge bases in the KE
2021-08-09 12:43:54:549 +0000 [qtp1752203484-16] INFO SmartConnectorLifeCycleApiServiceImpl - Returning response for smart connector with ID http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853
2021-08-09 12:43:54:569 +0000 [qtp1752203484-16] INFO SmartConnectorLifeCycleApiServiceImpl - Creating smart connector with ID http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853.
2021-08-09 12:44:02:916 +0000 [qtp1752203484-18] INFO MessageDispatcher - Notifying 2 listeners about the 2 knowledge bases in the KE
2021-08-09 12:44:02:949 +0000 [qtp1752203484-18] INFO SmartConnectorLifeCycleApiServiceImpl - Creating smart connector with ID http://www.example.org/kb-5a69e814-9d1c-42c3-ad2c-d56db3f9a39d.
2021-08-09 12:44:03:300 +0000 [pool-5-thread-1] ERROR SPARQL - [line: 1, col: 212] Bad IRI: 'http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/answer/act/satisfaction': <http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/answer/act/satisfaction> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
2021-08-09 12:44:58:040 +0000 [qtp1752203484-18] INFO KnowledgeInteractionLifeCycleApiServiceImpl - scKiPost called: class ReactKnowledgeInteraction {
    class KnowledgeInteractionBase {
        knowledgeInteractionType: ReactKnowledgeInteraction
        communicativeAct: class CommunicativeAct {
            requiredPurposes: [https://www.tno.nl/energy/ontology/interconnect#InformPurpose]
            satisfiedPurposes: [https://www.tno.nl/energy/ontology/interconnect#InformPurpose]
        }
    }
    argumentGraphPattern: ?s ?p ?o
    resultGraphPattern: ?a ?b ?c
}
2021-08-09 12:44:58:063 +0000 [qtp1752203484-18] ERROR SPARQL - [line: 1, col: 13] Bad IRI: 'http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement': <http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
2021-08-09 12:44:58:089 +0000 [qtp1752203484-18] WARN ServletHandler - 
javax.servlet.ServletException: org.apache.jena.query.QueryException: [line: 1, col: 13] Bad IRI: 'http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement': <http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.jena.query.QueryException: [line: 1, col: 13] Bad IRI: 'http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement': <http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
        at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:112)
        at org.apache.jena.sparql.lang.ParserARQ.parse$(ParserARQ.java:52)
        at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
        at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:144)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:83)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:56)
        at org.apache.jena.query.ParameterizedSparqlString.asQuery(ParameterizedSparqlString.java:1476)
        at org.apache.jena.query.ParameterizedSparqlString.asQuery(ParameterizedSparqlString.java:1463)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.InteractionProcessorImpl.communicativeActMatcher(InteractionProcessorImpl.java:280)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.InteractionProcessorImpl.lambda$3(InteractionProcessorImpl.java:153)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.InteractionProcessorImpl.processPostFromKnowledgeBase(InteractionProcessorImpl.java:155)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.MetaKnowledgeBaseImpl.knowledgeInteractionRegistered(MetaKnowledgeBaseImpl.java:476)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.KnowledgeBaseStoreImpl.lambda$17(KnowledgeBaseStoreImpl.java:196)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.KnowledgeBaseStoreImpl.register(KnowledgeBaseStoreImpl.java:196)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.SmartConnectorImpl.register(SmartConnectorImpl.java:236)
        at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.register(RestKnowledgeBase.java:346)
        at eu.interconnectproject.knowledge_engine.rest.api.impl.KnowledgeInteractionLifeCycleApiServiceImpl.scKiPost(KnowledgeInteractionLifeCycleApiServiceImpl.java:49)
        at eu.interconnectproject.knowledge_engine.rest.api.KnowledgeInteractionLifeCycleApi.scKiPost(KnowledgeInteractionLifeCycleApi.java:97)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
        ... 18 more
Caused by: org.apache.jena.riot.RiotException: [line: 1, col: 13] Bad IRI: 'http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement': <http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
        at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:146)
        at org.apache.jena.sparql.lang.QueryParserBase.resolveIRI(QueryParserBase.java:298)
        at org.apache.jena.sparql.lang.QueryParserBase.resolveQuotedIRI(QueryParserBase.java:282)
        at org.apache.jena.sparql.lang.arq.ARQParser.IRIREF(ARQParser.java:6354)
        at org.apache.jena.sparql.lang.arq.ARQParser.iri(ARQParser.java:6294)
        at org.apache.jena.sparql.lang.arq.ARQParser.GraphTerm(ARQParser.java:4378)
        at org.apache.jena.sparql.lang.arq.ARQParser.VarOrTerm(ARQParser.java:4203)
        at org.apache.jena.sparql.lang.arq.ARQParser.TriplesSameSubjectPath(ARQParser.java:3344)
        at org.apache.jena.sparql.lang.arq.ARQParser.TriplesBlock(ARQParser.java:2494)
        at org.apache.jena.sparql.lang.arq.ARQParser.GroupGraphPatternSub(ARQParser.java:2407)
        at org.apache.jena.sparql.lang.arq.ARQParser.GroupGraphPattern(ARQParser.java:2369)
        at org.apache.jena.sparql.lang.arq.ARQParser.WhereClause(ARQParser.java:852)
        at org.apache.jena.sparql.lang.arq.ARQParser.AskQuery(ARQParser.java:713)
        at org.apache.jena.sparql.lang.arq.ARQParser.Query(ARQParser.java:43)
        at org.apache.jena.sparql.lang.arq.ARQParser.QueryUnit(ARQParser.java:22)
        at org.apache.jena.sparql.lang.ParserARQ$1.exec(ParserARQ.java:48)
        at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:96)
        ... 65 more
2021-08-09 12:44:58:100 +0000 [qtp1752203484-18] WARN HttpChannel - /rest/sc/ki
javax.servlet.ServletException: org.apache.jena.query.QueryException: [line: 1, col: 13] Bad IRI: 'http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement': <http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.jena.query.QueryException: [line: 1, col: 13] Bad IRI: 'http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement': <http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
        at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:112)
        at org.apache.jena.sparql.lang.ParserARQ.parse$(ParserARQ.java:52)
        at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
        at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:144)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:83)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:56)
        at org.apache.jena.query.ParameterizedSparqlString.asQuery(ParameterizedSparqlString.java:1476)
        at org.apache.jena.query.ParameterizedSparqlString.asQuery(ParameterizedSparqlString.java:1463)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.InteractionProcessorImpl.communicativeActMatcher(InteractionProcessorImpl.java:280)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.InteractionProcessorImpl.lambda$3(InteractionProcessorImpl.java:153)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.InteractionProcessorImpl.processPostFromKnowledgeBase(InteractionProcessorImpl.java:155)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.MetaKnowledgeBaseImpl.knowledgeInteractionRegistered(MetaKnowledgeBaseImpl.java:476)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.KnowledgeBaseStoreImpl.lambda$17(KnowledgeBaseStoreImpl.java:196)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.KnowledgeBaseStoreImpl.register(KnowledgeBaseStoreImpl.java:196)
        at eu.interconnectproject.knowledge_engine.smartconnector.impl.SmartConnectorImpl.register(SmartConnectorImpl.java:236)
        at eu.interconnectproject.knowledge_engine.rest.api.impl.RestKnowledgeBase.register(RestKnowledgeBase.java:346)
        at eu.interconnectproject.knowledge_engine.rest.api.impl.KnowledgeInteractionLifeCycleApiServiceImpl.scKiPost(KnowledgeInteractionLifeCycleApiServiceImpl.java:49)
        at eu.interconnectproject.knowledge_engine.rest.api.KnowledgeInteractionLifeCycleApi.scKiPost(KnowledgeInteractionLifeCycleApi.java:97)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
        ... 18 more
Caused by: org.apache.jena.riot.RiotException: [line: 1, col: 13] Bad IRI: 'http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement': <http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
        at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:146)
        at org.apache.jena.sparql.lang.QueryParserBase.resolveIRI(QueryParserBase.java:298)
        at org.apache.jena.sparql.lang.QueryParserBase.resolveQuotedIRI(QueryParserBase.java:282)
        at org.apache.jena.sparql.lang.arq.ARQParser.IRIREF(ARQParser.java:6354)
        at org.apache.jena.sparql.lang.arq.ARQParser.iri(ARQParser.java:6294)
        at org.apache.jena.sparql.lang.arq.ARQParser.GraphTerm(ARQParser.java:4378)
        at org.apache.jena.sparql.lang.arq.ARQParser.VarOrTerm(ARQParser.java:4203)
        at org.apache.jena.sparql.lang.arq.ARQParser.TriplesSameSubjectPath(ARQParser.java:3344)
        at org.apache.jena.sparql.lang.arq.ARQParser.TriplesBlock(ARQParser.java:2494)
        at org.apache.jena.sparql.lang.arq.ARQParser.GroupGraphPatternSub(ARQParser.java:2407)
        at org.apache.jena.sparql.lang.arq.ARQParser.GroupGraphPattern(ARQParser.java:2369)
        at org.apache.jena.sparql.lang.arq.ARQParser.WhereClause(ARQParser.java:852)
        at org.apache.jena.sparql.lang.arq.ARQParser.AskQuery(ARQParser.java:713)
        at org.apache.jena.sparql.lang.arq.ARQParser.Query(ARQParser.java:43)
        at org.apache.jena.sparql.lang.arq.ARQParser.QueryUnit(ARQParser.java:22)
        at org.apache.jena.sparql.lang.ParserARQ$1.exec(ParserARQ.java:48)
        at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:96)
        ... 65 more
2021-08-09 12:44:58:105 +0000 [qtp1752203484-18] WARN HttpChannel - Could not send response error 500: javax.servlet.ServletException: org.apache.jena.query.QueryException: [line: 1, col: 13] Bad IRI: 'http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement': <http:////www.example.org/kb-ceb11b99-0d18-4403-a68d-1720475da853/meta/knowledgeinteractions/post/changed/act/requirement> Code: 57/REQUIRED_COMPONENT_MISSING in HOST: A component that is required by the scheme is missing.
```
</details>

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Aug 9, 2021, 12:47

created merge request !196 to address this issue

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Aug 9, 2021, 12:48

Aha, thanks for checking out the logs, @han.kruiger.tno.nl .

It seems that the KE is correct in rejecting the incorrect IRI, but apparently it should do it earlier (i.e. when the KB is registered) and it should not give a status 500.

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Aug 9, 2021, 13:10

mentioned in commit 2c3e03cbf87fb1b03026cb98102e26d9ad14c52a

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Aug 9, 2021, 13:27

Should be fixed in the next release.

**Comment by Sophietje** [comment]
In GitLab by @jarne.kerkaert.inetum-realdolmen.world on Aug 9, 2021, 13:59

@han.kruiger.tno.nl Thanks for acting so quickly! Would it be possible to already do a restart? Or would that cause problems for other partners?

The reason I ask, is because any tasks that involve our deployed services are blocked, as it's impossible to register interactions right now.

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Aug 9, 2021, 14:17

I understand, we're trying to deploy it this afternoon.

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Aug 9, 2021, 15:44

We deployed the SAME version of the knowledge engine this afternoon, so it should be in a normal state again.

However, since the root issue is not fixed in the deployed version, it may come up again if one of those invalid IRIs is given.

Unfortunately, we were unable to (confidently) deploy the newer version because we are running into some issues related to the distributed knowledge engine. Hopefully we'll release the newer version later this week! (Or otherwise we could backport it...?)
