### ISSUE TITLE
NullPointerExceptions in log of cloud version.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#277]
In GitLab by @barry.nouwt.tno.nl on Aug 17, 2021, 06:47

Not sure what goes wrong here. It happens in the Smart Connector of `kb_tiko_ask4`. It sends out a post (is it meta or regular?) and receives a react message. Then somehow the from graph pattern is `null`.

```
java.lang.NullPointerException
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.GraphPatternMatcher$GraphInfo.<init>(GraphPatternMatcher.java:338)
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.GraphPatternMatcher.transformBindingSet(GraphPatternMatcher.java:48)
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.SerialMatchingProcessor.lambda$checkOtherKnowledgeInteraction$1(SerialMatchingProcessor.java:152)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at eu.interconnectproject.knowledge_engine.smartconnector.impl.MessageRouterImpl.handleReactMessage(MessageRouterImpl.java:146)
	at eu.interconnectproject.knowledge_engine.smartconnector.runtime.messaging.LocalSmartConnectorConnection.lambda$deliverToLocalSmartConnector$0(LocalSmartConnectorConnection.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 1, 2022, 12:33

Does not seem to occur anymore.
