### ISSUE TITLE
Find origin of NullPointerExceptions in log file.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#305]
In GitLab by @barry.nouwt.tno.nl on Oct 14, 2021, 10:00

```
2021-10-05 15:30:56:262 +0100 [pool-15-thread-1] ERROR SerialMatchingProcessor-kb_test_answer_wings - Receiving a react message should succeed.
java.lang.NullPointerException
	at eu.knowledge.engine.smartconnector.impl.GraphPatternMatcher$GraphInfo.<init>(GraphPatternMatcher.java:338)
	at eu.knowledge.engine.smartconnector.impl.GraphPatternMatcher.transformBindingSet(GraphPatternMatcher.java:48)
	at eu.knowledge.engine.smartconnector.impl.SerialMatchingProcessor.lambda$checkOtherKnowledgeInteraction$1(SerialMatchingProcessor.java:152)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at eu.knowledge.engine.smartconnector.impl.MessageRouterImpl.handleReactMessage(MessageRouterImpl.java:146)
	at eu.knowledge.engine.smartconnector.runtime.messaging.LocalSmartConnectorConnection.lambda$deliverToLocalSmartConnector$0(LocalSmartConnectorConnection.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Apr 1, 2022, 12:51

Already resolved itself!
