### ISSUE TITLE
Find origin of queue full exceptions in log file.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#306]
In GitLab by @barry.nouwt.tno.nl on Oct 14, 2021, 10:01

```
java.lang.IllegalStateException: Queue full
	at java.base/java.util.AbstractQueue.add(AbstractQueue.java:98)
	at java.base/java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:326)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.toBeProcessedByKnowledgeBase(RestKnowledgeBase.java:243)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase$1.answerAsync(RestKnowledgeBase.java:120)
	at eu.knowledge.engine.smartconnector.impl.InteractionProcessorImpl.processAskFromMessageRouter(InteractionProcessorImpl.java:191)
	at eu.knowledge.engine.smartconnector.impl.MessageRouterImpl.handleAskMessage(MessageRouterImpl.java:82)
	at eu.knowledge.engine.smartconnector.runtime.messaging.LocalSmartConnectorConnection.lambda$deliverToLocalSmartConnector$0(LocalSmartConnectorConnection.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The queue has a max capacity of 50.

## Solution

Delete the oldest handle request, and complete the future exceptionally with a sane error. Make sure to test that we indeed catch this exception (that it reaches 'the other side'). Can we add something to the `ExchangeInfo`?

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Nov 12, 2021, 12:15

created merge request !231 to address this issue

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Dec 3, 2021, 08:30

https://gitlab.inesctec.pt/interconnect/generic-adapter/-/issues/66 might be related?

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Dec 3, 2021, 14:28

# Current behaviour when reactive KB doesn't respond

When the 51st knowledge request is initiated from a proactive KI, the 1st knowledge request hangs indefinitely.

# Preferred behaviour when reactive KB doesn't respond

When the 51st knowledge request is initiated from a proactive KI, the 1st knowledge request returns with no bindings from the unresponding KB, and with information in `exchangeInfo` that indicates that one of the nodes was unable to answer.

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Dec 3, 2021, 16:00

The preferred behaviour now works in a single runtime, but the error messages are not yet communicated between different runtimes.
