### ISSUE TITLE
SC deleted multiple times: Illegal state?

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#314]
In GitLab by @han.kruiger.tno.nl on Oct 29, 2021, 12:20

```
2021-10-01 17:45:41:142 +0100 [qtp1500056228-268] INFO SmartConnectorLifeCycleApiServiceImpl - scDelete called: https://ke.interconnectproject.eu/adapter/bd4055c0c983ae4f95db18f47dafe74837f79a47557009c7bcd3ecbfcc8aff2bf5ce58cfaa5045025cff5ba5a26fe97be7867cd9a459c64ccea9b0b045fb6d78
2021-10-01 17:45:41:156 +0100 [qtp1500056228-271] INFO SmartConnectorLifeCycleApiServiceImpl - scDelete called: https://ke.interconnectproject.eu/adapter/bd4055c0c983ae4f95db18f47dafe74837f79a47557009c7bcd3ecbfcc8aff2bf5ce58cfaa5045025cff5ba5a26fe97be7867cd9a459c64ccea9b0b045fb6d78
2021-10-01 17:45:41:158 +0100 [qtp1500056228-271] WARN ServletHandler - 
javax.servlet.ServletException: java.lang.IllegalStateException: The SmartConnector cannot be used anymore once it is stopped
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: The SmartConnector cannot be used anymore once it is stopped
	at eu.knowledge.engine.smartconnector.impl.SmartConnectorImpl.checkStopped(SmartConnectorImpl.java:473)
	at eu.knowledge.engine.smartconnector.impl.SmartConnectorImpl.stop(SmartConnectorImpl.java:451)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.stop(RestKnowledgeBase.java:616)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBaseManager.deleteKB(RestKnowledgeBaseManager.java:77)
	at eu.knowledge.engine.rest.api.impl.SmartConnectorLifeCycleApiServiceImpl.scDelete(SmartConnectorLifeCycleApiServiceImpl.java:149)
	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	... 18 more
```

## Solution

`RestKnowledgeBaseManager.deleteKB` should return a boolean and we should return 404 when the deletion failed.

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Oct 29, 2021, 14:44

I could reproduce this by doing a POST request for registering a KB and then doing two DELETE requests in parallel to remove it:

```bash
# Register
curl --location --request POST 'localhost:8280/rest/sc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "knowledgeBaseId": "http://www.example.org/kb-14d25aa6-7580-4210-95fd-dcc4350a7608",
    "knowledgeBaseName": "Knowledge Base name",
    "knowledgeBaseDescription": "Knowledge Base Description"
}'

# Delete twice!

curl --location --request DELETE 'localhost:8280/rest/sc' \
--header 'Knowledge-Base-Id: http://www.example.org/kb-14d25aa6-7580-4210-95fd-dcc4350a7608' \
--data-raw '' & curl --location --request DELETE 'localhost:8280/rest/sc' \
--header 'Knowledge-Base-Id: http://www.example.org/kb-14d25aa6-7580-4210-95fd-dcc4350a7608' \
--data-raw ''

```

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Oct 29, 2021, 14:46

created merge request !228 to address this issue

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Oct 29, 2021, 15:02

mentioned in commit ea44636265b33e9fe092518ef45b45c32b6c53e3
