### ISSUE TITLE
Inactivity suspension functionality should not throw exceptions.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#351]
In GitLab by @barry.nouwt.tno.nl on Jan 27, 2022, 12:30

In the knowledge engine log file (of PROD), we see a few exceptions like the following:

```
2022-01-24 13:23:09:681 +0000 [Timer-18621] WARN RestKnowledgeBase - Suspending KB https://ke.interconnectproject.eu/adapter/e1f71c6a0e95c138120780dad597fc2c4a42291980befa1ca5d325a1c1995d543009f8ddf139a3b05a5d8144d451d0d67ec41561f46396628873696e3c88e160 because of inactivity.
Exception in thread "Timer-18621" java.lang.IllegalStateException: The SmartConnector cannot be used anymore once it is stopped
        at eu.knowledge.engine.smartconnector.impl.SmartConnectorImpl.checkStopped(SmartConnectorImpl.java:473)
        at eu.knowledge.engine.smartconnector.impl.SmartConnectorImpl.stop(SmartConnectorImpl.java:451)
        at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.stop(RestKnowledgeBase.java:654)
        at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.suspend(RestKnowledgeBase.java:737)
        at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase$3.run(RestKnowledgeBase.java:722)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
```

There are also some NullPointerExceptions that seem related to the inactivity checker. So, let's figure out how these are caused and make sure they cannot occur again.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Jan 27, 2022, 12:32

Or was this exception already solved on `master`, @han.kruiger.tno.nl ?

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jan 27, 2022, 14:32

Yes, this was merged in !254, I think.

I am not 100% sure, because the thing you pasted doesn't look like an exception, but some JSON.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Jan 27, 2022, 14:34

Whoops, that's indeed not the exception but something else :smile: .

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Jan 27, 2022, 14:36

Now it contains an Exception.

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jan 27, 2022, 14:43

:thumbsup: It could be that the SC has been manually deleted and the timeout isn't canceled so it also tries to do it after the timer runs out. I thought I fixed that in !250.

I will take a look tomorrow. To make sure I can always add a null check so the exception doesn't occur.

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jan 28, 2022, 09:44

created merge request !264 to address this issue

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jan 28, 2022, 10:08

mentioned in commit 8cf238e8ea9cfb01c022e1ed30cb811da399cba4
