### ISSUE TITLE
Meta Knowledge Interactions should pass binding validation

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#385]
In GitLab by @han.kruiger.tno.nl on Jun 3, 2022, 09:13

Currently, errors like these are thrown for our meta Knowledge Interactions when they exchange bindings:

```
2022-06-03 11:09:43:788 +0200 [pool-4-thread-1] ERROR InteractionProcessorImpl-kb1 - An error occurred while answering a msg: {}
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: KB gave outgoing binding Binding [map={sat=<https://www.tno.nl/kb1/meta/knowledgeinteractions/react/new/act/sat>, pattern="?kb <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.tno.nl/energy/ontology/interconnect#KnowledgeBase> . ?kb <https://www.tno.nl/energy/ontology/interconnect#hasName> ?name . ?kb <https://www.tno.nl/energy/ontology/interconnect#hasDescription> ?description . ?kb <https://www.tno.nl/energy/ontology/interconnect#hasKnowledgeInteraction> ?ki . ?ki <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?kiType . ?ki <https://www.tno.nl/energy/ontology/interconnect#isMeta> ?isMeta . ?ki <https://www.tno.nl/energy/ontology/interconnect#hasCommunicativeAct> ?act . ?act <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.tno.nl/energy/ontology/interconnect#CommunicativeAct> . ?act <https://www.tno.nl/energy/ontology/interconnect#hasRequirement> ?req . ?act <https://www.tno.nl/energy/ontology/interconnect#hasSatisfaction> ?sat . ?req <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?reqType . ?sat <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?satType . ?ki <https://www.tno.nl/energy/ontology/interconnect#hasGraphPattern> ?gp . ?gp <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?patternType . ?gp <https://www.tno.nl/energy/ontology/interconnect#hasPattern> ?pattern . ", description="description of kb1", gp=<https://www.tno.nl/kb1/meta/knowledgeinteractions/react/new/argumentgp>, isMeta=true, patternType=<https://www.tno.nl/energy/ontology/interconnect#ArgumentGraphPattern>, act=<https://www.tno.nl/kb1/meta/knowledgeinteractions/react/new/act>, kb=<https://www.tno.nl/kb1>, name="kb1", reqType=<https://www.tno.nl/energy/ontology/interconnect#NewKnowledgePurpose>, satType=<https://www.tno.nl/energy/ontology/interconnect#InformPurpose>, ki=<https://www.tno.nl/kb1/meta/knowledgeinteractions/react/new>, kiType=<https://www.tno.nl/energy/ontology/interconnect#ReactKnowledgeInteraction>, req=<https://www.tno.nl/kb1/meta/knowledgeinteractions/react/new/act/req>}], but this doesn't have a matching incoming binding!
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
        at eu.knowledge.engine.smartconnector.impl.InteractionProcessorImpl.processAskFromMessageRouter(InteractionProcessorImpl.java:221)
        at eu.knowledge.engine.smartconnector.impl.MessageRouterImpl.handleAskMessage(MessageRouterImpl.java:84)
        at eu.knowledge.engine.smartconnector.runtime.messaging.LocalSmartConnectorConnection.lambda$deliverToLocalSmartConnector$0(LocalSmartConnectorConnection.java:46)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: KB gave outgoing binding Binding [map={sat=<https://www.tno.nl/kb1/meta/knowledgeinteractions/react/new/act/sat>, pattern="?kb <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.tno.nl/energy/ontology/interconnect#KnowledgeBase> . ?kb <https://www.tno.nl/energy/ontology/interconnect#hasName> ?name . ?kb <https://www.tno.nl/energy/ontology/interconnect#hasDescription> ?description . ?kb <https://www.tno.nl/energy/ontology/interconnect#hasKnowledgeInteraction> ?ki . ?ki <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?kiType . ?ki <https://www.tno.nl/energy/ontology/interconnect#isMeta> ?isMeta . ?ki <https://www.tno.nl/energy/ontology/interconnect#hasCommunicativeAct> ?act . ?act <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://www.tno.nl/energy/ontology/interconnect#CommunicativeAct> . ?act <https://www.tno.nl/energy/ontology/interconnect#hasRequirement> ?req . ?act <https://www.tno.nl/energy/ontology/interconnect#hasSatisfaction> ?sat . ?req <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?reqType . ?sat <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?satType . ?ki <https://www.tno.nl/energy/ontology/interconnect#hasGraphPattern> ?gp . ?gp <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?patternType . ?gp <https://www.tno.nl/energy/ontology/interconnect#hasPattern> ?pattern . ", description="description of kb1", gp=<https://www.tno.nl/kb1/meta/knowledgeinteractions/react/new/argumentgp>, isMeta=true, patternType=<https://www.tno.nl/energy/ontology/interconnect#ArgumentGraphPattern>, act=<https://www.tno.nl/kb1/meta/knowledgeinteractions/react/new/act>, kb=<https://www.tno.nl/kb1>, name="kb1", reqType=<https://www.tno.nl/energy/ontology/interconnect#NewKnowledgePurpose>, satType=<https://www.tno.nl/energy/ontology/interconnect#InformPurpose>, ki=<https://www.tno.nl/kb1/meta/knowledgeinteractions/react/new>, kiType=<https://www.tno.nl/energy/ontology/interconnect#ReactKnowledgeInteraction>, req=<https://www.tno.nl/kb1/meta/knowledgeinteractions/react/new/act/req>}], but this doesn't have a matching incoming binding!
        at eu.knowledge.engine.smartconnector.api.BindingValidator.lambda$validateIncomingOutgoingAnswer$5(BindingValidator.java:114)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at eu.knowledge.engine.smartconnector.api.BindingValidator.validateIncomingOutgoingAnswer(BindingValidator.java:110)
        at eu.knowledge.engine.smartconnector.impl.InteractionProcessorImpl.lambda$processAskFromMessageRouter$2(InteractionProcessorImpl.java:225)
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
        ... 11 more
```

This is because we don't pass our own input/output binding validation. It seems like we just return __all__ KB/KI data when any meta ASK comes in. To solve this, we should filter out any bindings that do not have a corresponding input binding.

Solving this will also result in less wasted bandwidth! :thumbsup:

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on Jun 3, 2022, 09:24

created branch [`371-meta-knowledge-interactions-should-pass-binding-validation`](/interconnect/knowledge-engine/-/compare/master...371-meta-knowledge-interactions-should-pass-binding-validation) to address this issue

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Jun 3, 2022, 13:15

mentioned in commit 679c1994d46582fc2d51a7ef8248ddb1f0e8fa25
