### ISSUE TITLE
Validation null pointer exception

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#395]
In GitLab by @han.kruiger.tno.nl on Aug 2, 2022, 08:18

```
Caused by: java.lang.NullPointerException
	at eu.knowledge.engine.smartconnector.api.BindingValidator.validateIncomingOutgoingReact(BindingValidator.java:129)
	at eu.knowledge.engine.smartconnector.impl.InteractionProcessorImpl.lambda$processPostFromMessageRouter$5(InteractionProcessorImpl.java:309)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
```

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Nov 25, 2022, 09:16

Assumed to be fixed already.
