### ISSUE TITLE
Distributed mode of the KE

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#398]
In GitLab by @mel.3e.eu on Oct 20, 2022, 13:51

Hello,

While successfully using a local instance of the KE for our flexibility SSA, I need to shift to the distributed mode for POST/REACT interaction with the remote knowledge directory of the Cybergrid platform. Just to confirm:

1- I have set `KD_URL=https://kd.cyber-grid.com/`  and `KE_RUNTIME_PORT=8081` and  `KE_RUNTIME_EXPOSED_URL=9e64-185-174-184-98.eu.ngrok.io`. The last one is to expose the local port on 8081 for the KE runtime. The corresponding port 8081 is opened in the firewall.

2- I have started the KE on port 8280 with 
```
java -cp "smart-connector-rest-dist-1.1.2.jar;dependency/*" eu.knowledge.engi
ne.rest.Main 8280
```
It says: `2022-10-20 12:27:12:427 +0200 [main] INFO RestServer - Starting Knowledge Engine REST API on port 8280.`, but the issue is that I cannot access the `http://localhost:8081/runtimedetails` to check the KER.

Any thoughts on what could be the issue?

Thanks.

Kind regards,
Mojtaba

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Oct 21, 2022, 07:43

Hey @mel.3e.eu, thanks for contacting us! 

Did you try creating your Smart Connector via the REST API first, before accessing `http://localhost:8081/runtimedetails`?

The KERuntime only gets started after creating the first Smart Connector and it should print messages to the log about contacting the Knowledge Directory `https://kd.cyber-grid.com/`. Do you see such messages? It should look something like:

```
KnowledgeDirectoryConnection - Starting connection with Knowledge Directory at https://kd.cyber-grid.com/
```
Hope this helps!

Kind regards,

Barry

**Comment by Sophietje** [comment]
In GitLab by @mel.3e.eu on Oct 21, 2022, 14:24

Hi Barry,

Thank you very much for your detailed response. I see the SC's `runtimedatails` now via both the local host:8081 and the reverse proxy https://c5cb-2a02-a03f-6651-2800-6033-b69b-b767-e922.eu.ngrok.io/.

```
{
"runtimeId":null,
"smartConnectorIds":["https://ke.interconnectproject.eu/adapter/0082d83d7c76ef2dfeaf76b836adc094a9a7878e26305a800af4af432587cdaf93fb7907463776b186f190ba86d959136d3a19e700fda38c5372ec6c3c91aea7"]
}
```

Would you possibly know why the `runtimeID` is appearing as null? From the log:

```
2022-10-21 16:21:32:604 +0200 [pool-4-thread-1] ERROR RemoteKerConnectionManager - Error while querying the Knowledge Directory
java.lang.IllegalStateException: Can only retrieve Knowledge Directory infomation when REGISTERED or INTERRUPETD
        at eu.knowledge.engine.smartconnector.runtime.messaging.KnowledgeDirectoryConnection.getKnowledgeEngineRuntimeConnectionDetails(KnowledgeDirectory
Connection.java:132)
        at eu.knowledge.engine.smartconnector.runtime.messaging.KnowledgeDirectoryConnection.getOtherKnowledgeEngineRuntimeConnectionDetails(KnowledgeDire
ctoryConnection.java:154)
        at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.queryKnowledgeDirectory(RemoteKerConnectionManager.java:84)
        at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.scheduleQueryKnowledgeDirectory(RemoteKerConnectionManager.java
:70)
        at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.lambda$start$0(RemoteKerConnectionManager.java:56)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Thanks.

Kind regards,

Mojtaba

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Oct 21, 2022, 14:48

Hey @mel.3e.eu, glad you are a step further. 

Can you try and remove the trailing `/` on your `KD_URL`? So, instead of `KD_URL=https://kd.cyber-grid.com/` use `KD_URL=https://kd.cyber-grid.com`.

If that does not help, can you confirm that you see the following message (or similar) in your log:

```
2022-10-21 16:36:14:364 +0200 [pool-4-thread-1] INFO KnowledgeDirectoryConnection - Successfully registered at the Knowledge Directory https://kd.cyber-grid.com/
```
If not, do you see a warning like:
```
Could not register at Knowledge Directory https://kd.cyber-grid.com/, response was: ...
```
The `runtimeId` is `null` if the registration to the Knowledge Directory was unsuccessful.

Regards, Barry

**Comment by Sophietje** [comment]
In GitLab by @mel.3e.eu on Oct 21, 2022, 15:46

Thank you very much, Barry. Thanks to you, we made the SSA up and running together with Cybergrid. A nice end to the workweek!

Have a nice weekend.

Kind regards,

Mojtaba
