### ISSUE TITLE
Debug log of Knowledge Engine shows many TimeOutExceptions, related to read timeout in HTTP clients?

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#430]
In GitLab by @jorrit.nutma.tno.nl on May 23, 2023, 15:45

These kind of timeoutexceptions are logged many times (also after all smart connectors were destroyed).
```
2023-05-23 15:33:01:522 +0000 [Scheduler-1213216872] DEBUG IdleTimeout - SelectChannelEndPoint@1931f28d{/139.63.196.85:50404<->8280,Open,in,OSHUT,R,-,29994/30000,HttpConnection}{io=1,kio=1,kro=1} idle timeout check, elapsed: 29993 ms, remaining: 7 ms
2023-05-23 15:33:01:529 +0000 [Scheduler-1213216872] DEBUG IdleTimeout - SelectChannelEndPoint@1931f28d{/139.63.196.85:50404<->8280,Open,in,OSHUT,R,-,30001/30000,HttpConnection}{io=1,kio=1,kro=1} idle timeout check, elapsed: 30001 ms, remaining: -1 ms
2023-05-23 15:33:01:529 +0000 [Scheduler-1213216872] DEBUG IdleTimeout - SelectChannelEndPoint@1931f28d{/139.63.196.85:50404<->8280,Open,in,OSHUT,R,-,30001/30000,HttpConnection}{io=1,kio=1,kro=1} idle timeout expired
2023-05-23 15:33:01:529 +0000 [Scheduler-1213216872] DEBUG WriteFlusher - ignored: WriteFlusher@1081de19{IDLE} {}
java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
        at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2023-05-23 15:33:01:530 +0000 [Scheduler-1213216872] DEBUG AbstractEndPoint - Ignored idle endpoint SelectChannelEndPoint@1931f28d{/139.63.196.85:50404<->8280,Open,in,OSHUT,-,-,30002/30000,HttpConnection}{io=1,kio=1,kro=1}
2023-05-23 15:33:01:530 +0000 [qtp1318822808-18] DEBUG AbstractConnection - FILL_INTERESTED-->IDLE HttpConnection@e44c65d{IDLE}
2023-05-23 15:33:01:531 +0000 [qtp1318822808-18] DEBUG HttpParser - close HttpParser{s=CLOSED,0 of -1}
2023-05-23 15:33:01:531 +0000 [qtp1318822808-18] DEBUG HttpParser - CLOSED --> CLOSED
2023-05-23 15:33:01:531 +0000 [qtp1318822808-18] DEBUG AbstractConnection - HttpConnection@e44c65d{IDLE} onFillInterestedFailed {}
java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
        at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
        at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2023-05-23 15:33:01:531 +0000 [qtp1318822808-18] DEBUG AbstractEndPoint - onClose SelectChannelEndPoint@1931f28d{/139.63.196.85:50404<->8280,CLOSED,in,OSHUT,-,-,1/30000,HttpConnection}{io=1,kio=1,kro=1}
2023-05-23 15:33:01:531 +0000 [qtp1318822808-18] DEBUG ChannelEndPoint - close SelectChannelEndPoint@1931f28d{/139.63.196.85:50404<->8280,CLOSED,in,OSHUT,-,-,1/30000,HttpConnection}{io=1,kio=1,kro=1}
2023-05-23 15:33:01:537 +0000 [qtp1318822808-18] DEBUG SelectorManager - Destroyed SelectChannelEndPoint@1931f28d{/139.63.196.85:50404<->8280,CLOSED,ISHUT,OSHUT,-,-,6/30000,HttpConnection}{io=1,kio=-1,kro=-1}
2023-05-23 15:33:01:537 +0000 [qtp1318822808-18] DEBUG AbstractConnection - onClose HttpConnection@e44c65d{IDLE}
2023-05-23 15:33:01:537 +0000 [qtp1318822808-18] DEBUG AbstractEndPoint - onClose SelectChannelEndPoint@1931f28d{/139.63.196.85:50404<->8280,CLOSED,ISHUT,OSHUT,-,-,7/30000,HttpConnection}{io=1,kio=-1,kro=-1}
```

**Comment by Sophietje** [comment]
In GitLab by @jorrit.nutma.tno.nl on May 25, 2023, 07:27

this, btw, also happens after a HTTP GET from the browser on `rest/sc`

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 08:13

Hey @jorrit.nutma.tno.nl, I've not seen these stack traces in the logs before. Looking at the above logs I can think of two causes:
- The `...jetty.io.IdleTimeout` class could indicate that this happens in Jetty code and [this comment](https://github.com/eclipse/jetty.project/issues/4280#issuecomment-551843262) explains what might be causing this (an unresponsive client). The question is then what client is unresponsive and what operation was going on when this happened. A candidate might be the *longpolling* functionality, because this keeps connections open between the client and the server. You mention that all smart connectors were destroyed, but were they also correctly removed using the `HTTP DELETE` operation on the `rest/sc` endpoint?
- The `ScheduledThreadPoolExecutor` class that is mentioned in the stacktrace is also used [here](https://gitlab.inesctec.pt/interconnect/knowledge-engine/-/blob/master/smart-connector-rest-server/src/main/java/eu/knowledge/engine/rest/api/impl/RestKnowledgeBaseManager.java#L23) in the Knowledge Engine REST API to keep track of whether knowledge bases should be suspended because of inactivity, although Jetty's  `IdleTimeout` class indicates otherwise.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 13:53

marked #418 as a duplicate of this issue

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 13:53

marked this issue as related to #418

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 15:13

removed the relation with #418

**Comment by Sophietje** [comment]
In GitLab by @jorrit.nutma.tno.nl on Jun 5, 2023, 09:08

I've indeed removed the smart connector (at least the ones that were created by my code) with the HTTP DELETE on `rest/sc`. I don't know how the GA it does.

But the interesting thing is that the browser (Firefox) also causes the IdleTimeout to occur, apparently is also does a call that is not closed properly.

Maybe it could be that I am not assigning the result of the java function (that returns the result from the server) and therefore the client does not complete the read (like mentioned in the [issue](https://github.com/eclipse/jetty.project/issues/4280#issuecomment-551843262) you linked to).

**Comment by Sophietje** [comment]
In GitLab by @jorrit.nutma.tno.nl on Jun 7, 2023, 15:43

OK, one more clue. In the NL pilot setup I've seen the issue of the read timeout in ReFlex. It happens during a ASK KI call after a restart of ReFlex. The strange thing is that I don't have the timeout if I shut down the GA instance (v2.1) of NL pilot... Maybe the GA is holding some resources in the KE that it shouldn't?

I've reproduced this behavior everytime I tried.

Including @facoelho @aleksandar.tomcic.vizlore.com because of that.

@vasco.m.campos you were also have read timeout problems, right?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Jun 9, 2023, 08:42

Hey @jorrit.nutma.tno.nl, thanks for the clues :thumbsup:. I took some time to try and reproduce the exception above, but was unsuccesfull. I started a clean Knowledge Engine REST server (`1.2.1`) and created a single knowledge base (without GA) with an Answer KI using Postman. Reinitiated the longpolling GET /sc/handle a few times and also tried DELETE /sc while longpolling, but this particular TimeoutException does not show up. Did find some other incorrect behavior (see #420).

Some questions to see if we can pinpoint the error:
- Is it the distributed or non-distributed version of the Knowledge Engine?
- What version of the TKE is giving these timeouts: version 1.1.3, 1.2.0 or 1.2.1?
- Did these timeouts started to occur recently, or did they occur before as well?

**Comment by Sophietje** [comment]
In GitLab by @facoelho on Jun 9, 2023, 11:39

Vasco indeed reported timeouts some timeouts but SockeTimeoutExceptions. This against KE1.1.3. I was never able to reproduce it, and still those timeouts were quite sporadic. What you @jorrit.nutma.tno.nl report appears constant.  I will read carefully (I am currently travelling) what your report and try to reproduce. I do not discard that it could be within the GA. Next Monday I'll discuss this with @aleksandar.tomcic.vizlore.com

**Comment by Sophietje** [comment]
In GitLab by @jorrit.nutma.tno.nl on Jun 9, 2023, 16:29

non-distributed version, 1.1.3. The timeout problems has been around for a while. I've seen it happening already quite some months ago

**Comment by Sophietje** [comment]
In GitLab by @facoelho on Jun 14, 2023, 10:53

Hi @jorrit.nutma.tno.nl 
Me and @aleksandar.tomcic.vizlore.com  have been looking at this. 
Some of things regarding your test so that we are able to reproduce this:
1. Do you confirm  you are using an instance of the KE (v1.1.3) that is not the global one, correct?
2. Is the KE version you are using publicly available (which URL) so that we can test against it ?
3. You test scenario is: register SC, register Ask KI, ASK  and then the timeout arises. Do you confirm this ?
4. Did you change the configurations of the GA, namely the connect.timeout and read.timeout ?

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Jun 15, 2023, 11:55

Hi everyone, I took another look after I found out I did not read the issue very thoroughly, because it clearly says that the `Exception` occurs in the `DEBUG` log of the Knowledge Engine, while in my previous tests I only looked for the `Exception` in the `INFO` log. So, I repeated the small test but now with log level set to `DEBUG` and could reproduce the error:

```
2023-06-15 13:49:27:389 +0200 [Scheduler-431687835] DEBUG IdleTimeout - SelectChannelEndPoint@256c13e6{/[0:0:0:0:0:0:0:1]:56749<->8280,Open,in,out,R,-,27310/30000,HttpConnection}{io=1,kio=1,kro=1} idle timeout check, elapsed: 27310 ms, remaining: 2690 ms
2023-06-15 13:49:30:088 +0200 [Scheduler-431687835] DEBUG IdleTimeout - SelectChannelEndPoint@256c13e6{/[0:0:0:0:0:0:0:1]:56749<->8280,Open,in,out,R,-,30009/30000,HttpConnection}{io=1,kio=1,kro=1} idle timeout check, elapsed: 30009 ms, remaining: -9 ms
2023-06-15 13:49:30:088 +0200 [Scheduler-431687835] DEBUG IdleTimeout - SelectChannelEndPoint@256c13e6{/[0:0:0:0:0:0:0:1]:56749<->8280,Open,in,out,R,-,30009/30000,HttpConnection}{io=1,kio=1,kro=1} idle timeout expired
2023-06-15 13:49:30:088 +0200 [Scheduler-431687835] DEBUG WriteFlusher - ignored: WriteFlusher@b9c02a1{IDLE} {}
java.util.concurrent.TimeoutException: Idle timeout expired: 30009/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-06-15 13:49:30:088 +0200 [qtp870698190-55] DEBUG AbstractConnection - FILL_INTERESTED-->IDLE HttpConnection@69b82673{IDLE}
2023-06-15 13:49:30:088 +0200 [Scheduler-431687835] DEBUG AbstractEndPoint - Ignored idle endpoint SelectChannelEndPoint@256c13e6{/[0:0:0:0:0:0:0:1]:56749<->8280,Open,in,out,-,-,30009/30000,HttpConnection}{io=1,kio=1,kro=1}
2023-06-15 13:49:30:088 +0200 [qtp870698190-55] DEBUG HttpParser - close HttpParser{s=START,0 of -1}
2023-06-15 13:49:30:088 +0200 [qtp870698190-55] DEBUG HttpParser - START --> CLOSED
2023-06-15 13:49:30:088 +0200 [qtp870698190-55] DEBUG AbstractConnection - HttpConnection@69b82673{IDLE} onFillInterestedFailed {}
java.util.concurrent.TimeoutException: Idle timeout expired: 30009/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-06-15 13:49:30:088 +0200 [qtp870698190-55] DEBUG ChannelEndPoint - oshut SelectChannelEndPoint@256c13e6{/[0:0:0:0:0:0:0:1]:56749<->8280,Open,in,out,-,-,0/30000,HttpConnection}{io=1,kio=1,kro=1}
2023-06-15 13:49:30:088 +0200 [qtp870698190-55] DEBUG AbstractConnection - fillInterested HttpConnection@69b82673{IDLE}
```

The steps to reproduce were:
- Start Knowledge Engine REST Server
- register KB1 and KB2
- register KB1 ANSWER and KB2 ASK
- start `GET /handle` of KB1
- active ASK of KB2
- do a `POST /handle` with the answer data
- wait a while and search for `Exception` in the log of the KE.

@facoelho I think we can confirm that the Generic Adapter is not causing this issue, because I did not use one and it showed up :thumbsup: 

I did not yet took the time to find the cause, but we can do that some other time.

Regards, Barry

**Comment by Sophietje** [comment]
In GitLab by @facoelho on Jun 15, 2023, 12:41

@barry.nouwt.tno.nl thanks for the clarification.

**Comment by Sophietje** [comment]
In GitLab by @jorrit.nutma.tno.nl on Sep 13, 2023, 14:15

Ok, I am having this issue https://gitlab.inesctec.pt/interconnect/pilot-devops-planning/-/issues/73 and I am wondering if it's related. Not sure if that really is the case because because it is clear the the TimeOutException also happens in other cases (e.g., after a browser request and when Barry registered his KBs).  Anyhow, the issue with timeout in client is really bugging me so if that timeout is somehow caused by the one this issue is about, then I would be really happy if it would be fixed.

To provide some more details about the timeout in the clients, here is a stacktrace:

```plaintext
nl.tno.reflex.device.comm.ke.client.ApiException: java.net.SocketTimeoutException: timeout
        at nl.tno.reflex.device.comm.ke.client.ApiClient.execute(ApiClient.java:924)
        at nl.tno.reflex.device.comm.ke.client.api.ProactiveApi.scAskPostWithHttpInfo(ProactiveApi.java:181)
        at nl.tno.reflex.device.comm.ke.client.api.ProactiveApi.scAskPost(ProactiveApi.java:157)
        at nl.tno.reflex.device.comm.ke.RestKeSpineConnection.askInitialDevices(RestKeSpineConnection.java:214)
        at nl.tno.reflex.device.comm.ke.RestKeSpineConnection.activate(RestKeSpineConnection.java:86)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317)
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:341)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:983)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:956)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:901)
        at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:349)
        at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:249)
        at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:362)
        at org.apache.felix.framework.Felix.getService(Felix.java:3984)
        at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:450)
        at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:38)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:944)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:872)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:904)
        at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
        at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
        at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4863)
        at org.apache.felix.framework.Felix.registerService(Felix.java:3834)
        at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:906)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:892)
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:959)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:732)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.reconfigure(SingleComponentManager.java:735)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.reconfigure(SingleComponentManager.java:674)
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.configurationUpdated(ConfigurableComponentHolder.java:435)
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:317)
        at org.apache.felix.scr.impl.manager.RegionConfigurationSupport$2.configurationEvent(RegionConfigurationSupport.java:119)
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:1685)
        at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:1637)
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138)
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.net.SocketTimeoutException: timeout
        at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147)
        at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:161)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:339)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at nl.tno.reflex.device.comm.ke.client.ApiClient.execute(ApiClient.java:920)
        ... 51 common frames omitted
Caused by: java.net.SocketException: Socket closed
        at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:248)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:327)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:976)
        at okio.InputStreamSource.read(JvmOkio.kt:94)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
        ... 69 common frames omitted
```

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Sep 19, 2023, 12:31

According to [this](https://stackoverflow.com/a/67792440) answer, Jetty's `DEBUG`-level `TimeoutException`s are the consequence of not closing the HTTP connection by adding the `Connection: close` header to your request (apparently connections are permanent by default in `HTTP/1.1`). So, because a permanent HTTP connection is requested, Jetty starts a timer for 30 seconds and when the connection is idle for that period of time, it logs the timeout and probably closes the HTTP connection. I can also easily reproduce this by just sending a `GET /rest/sc` request (without the `Connection: close`) and wait for 30 seconds. This also means that the `Exception` should not occur when we do the same request *with* the `Connection: close` header and after testing this, I can confirm this is indeed what is happening. 

I think we can conclude that the TimeoutException is related to each request (because it starts a permanent connection), but is unrelated to the client timeouts that @jorrit.nutma.tno.nl experiences.

**Comment by Sophietje** [comment]
In GitLab by @jorrit.nutma.tno.nl on Sep 19, 2023, 14:48

We also found the real cause for the timeouts in the client so we can close this issue.
