### ISSUE TITLE
KER cannot connect to cyber-grid's Knowledge Directory that is secured with Basic Authentication

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#431]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 10:58

The bug is that when the KER connects to the KD it provided the basic auth user credentials both through the ‘Authentication’ header and the URL, which causes the NGINX reverse proxy (from AWS?) in front of the cyber-grid KD to respond with a 404. After changing the KE code to remove the user credentials from the URL and only send it through ‘Authentication’ header, the KER could successfully register with the KD with basic authentication. We did not previously find this bug, because the NGINX in our [authentication example](https://gitlab.inesctec.pt/interconnect/knowledge-engine/-/tree/master/examples/authentication) was configured differently and did not mind receiving the user credentials via both the `Authentication` and the URL.

```
2023-05-26 14:22:52:396 +0100 [pool-15-thread-1] ERROR RemoteKerConnectionManager - Error while querying the Knowledge Directory
java.lang.IllegalStateException: Can only retrieve Knowledge Directory infomation when REGISTERED or INTERRUPETD
at eu.knowledge.engine.smartconnector.runtime.messaging.KnowledgeDirectoryConnection.getKnowledgeEngineRuntimeConnectionDetails(KnowledgeDirectoryConnection.java:132)
at eu.knowledge.engine.smartconnector.runtime.messaging.KnowledgeDirectoryConnection.getOtherKnowledgeEngineRuntimeConnectionDetails(KnowledgeDirectoryConnection.java:154)
at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.queryKnowledgeDirectory(RemoteKerConnectionManager.java:84)
at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.scheduleQueryKnowledgeDirectory(RemoteKerConnectionManager.java:70)
at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.lambda$start$0(RemoteKerConnectionManager.java:56)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on May 26, 2023, 11:13

created branch [`417-ker-cannot-connect-to-cyber-grid-s-knowledge-directory-that-is-secured-with-basic-authentication`](/interconnect/knowledge-engine/-/compare/master...417-ker-cannot-connect-to-cyber-grid-s-knowledge-directory-that-is-secured-with-basic-authentication) to address this issue

**Comment by Sophietje** [comment]
In GitLab by @han.kruiger.tno.nl on May 26, 2023, 13:03

mentioned in commit 6f38652177e7baf8a61f11230ba28a78c32a3cd4

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 15:14

marked this issue as related to #418
