### ISSUE TITLE
Started to observe errors related with connection with KD

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#432]
In GitLab by @facoelho on May 26, 2023, 13:26

Hi. 
In the KE instance we have set up for the PT pilot, that is connected to cybergrids KD, I started to collect the error bellow upon start time. 
Is this of concern? 

2023-05-26 14:22:52:396 +0100 [pool-15-thread-1] ERROR RemoteKerConnectionManager - Error while querying the Knowledge Directory
java.lang.IllegalStateException: Can only retrieve Knowledge Directory infomation when REGISTERED or INTERRUPETD
        at eu.knowledge.engine.smartconnector.runtime.messaging.KnowledgeDirectoryConnection.getKnowledgeEngineRuntimeConnectionDetails(KnowledgeDirectoryConnection.java:132)
        at eu.knowledge.engine.smartconnector.runtime.messaging.KnowledgeDirectoryConnection.getOtherKnowledgeEngineRuntimeConnectionDetails(KnowledgeDirectoryConnection.java:154)
        at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.queryKnowledgeDirectory(RemoteKerConnectionManager.java:84)
        at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.scheduleQueryKnowledgeDirectory(RemoteKerConnectionManager.java:70)
        at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.lambda$start$0(RemoteKerConnectionManager.java:56)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 13:53

marked this issue as a duplicate of #416

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 13:53

marked this issue as related to #416

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 13:54

Hi @facoelho, it is a bug (see #417) in version 1.2.0 which is already solved. We are releasing a version 1.2.1 as we speak and I'll send a message to the project when it is done.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 15:13

removed the relation with #416

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on May 26, 2023, 15:14

marked this issue as related to #417
