### ISSUE TITLE
The `RestKnowledgeBase.asyncResponse` should be `cancel()`-ed when a `RestKnowledgeBase` is `stop()`-ed

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#434]
In GitLab by @barry.nouwt.tno.nl on Jun 9, 2023, 08:02

While trying to reproduce issue #416, I wondered whether a client-side cancel of the longpolling request also cancels the `asyncResponse` on the server side. Because what would happen if the server thinks the asyncResponse is still alive, while the client already cancelled their longpolling request? This might cause something described in #416 (TimeoutException) to happen on the server side (although I am not able to reproduce it).

And different, but related is why the `asyncResponse` on the server side is not cancelled when a `RestKnowledgeBase` is [stopped](https://gitlab.inesctec.pt/interconnect/knowledge-engine/-/blob/master/smart-connector-rest-server/src/main/java/eu/knowledge/engine/rest/api/impl/RestKnowledgeBase.java#L709-713).

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Jun 9, 2023, 08:03

created branch [`420-the-restknowledgebase-asyncresponse-should-be-cancel-ed-when-a-restknowledgebase-is-stop-ed`](/interconnect/knowledge-engine/-/compare/master...420-the-restknowledgebase-asyncresponse-should-be-cancel-ed-when-a-restknowledgebase-is-stop-ed) to address this issue

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Jun 9, 2023, 08:36

Related to this `cancel()` and `stop()` interaction, the following error occurs when a KB is stopped while in the process of answering:

```
2023-06-09 10:33:03:695 +0200 [qtp870698190-30] ERROR InteractionProcessorImpl-Knowledge Base name - An error occurred while answering a msg: 
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "eu.knowledge.engine.smartconnector.api.BindingSet.forEach(java.util.function.Consumer)" because "outgoing" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2480)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.lambda$11(RestKnowledgeBase.java:739)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.cancelAndClearAllHandleRequests(RestKnowledgeBase.java:738)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.stop(RestKnowledgeBase.java:731)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBaseManager.deleteKB(RestKnowledgeBaseManager.java:122)
	at eu.knowledge.engine.rest.api.impl.SmartConnectorLifeCycleApiServiceImpl.scDelete(SmartConnectorLifeCycleApiServiceImpl.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "eu.knowledge.engine.smartconnector.api.BindingSet.forEach(java.util.function.Consumer)" because "outgoing" is null
	at eu.knowledge.engine.smartconnector.api.BindingValidator.validateIncomingOutgoingAnswer(BindingValidator.java:110)
	at eu.knowledge.engine.smartconnector.impl.InteractionProcessorImpl.lambda$2(InteractionProcessorImpl.java:225)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 48 more
```

The error `because "outgoing" is null` is propagated to the asking KB and the ExchangeInfo indicates the data exchange failed for that reason. So, that seems to work fine, but maybe we can improve this message to something like 'The KB stopped while answering, so the data exchange failed.'.

To reproduce:
- start Postman
- register KB1
- register KB2
- register KB1 answer
- register KB2 ask
- start long polling KB1
- cancel long polling KB1 client side
- start KB2 ask
- stop KB1 (either by waiting until it is suspended or using the `DELETE /sc` REST operation.
- see exception above when deliberately stopping and something similar when the KB is automatically suspended (i.e. stopped) by the server.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Aug 8, 2023, 13:51

mentioned in commit 2aab807491ef364016d0f16b7b72182c8a4da3c9
