### ISSUE TITLE
The ConcurrentModificationException in MessageDispatcher should not occur.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#436]
In GitLab by @barry.nouwt.tno.nl on Jun 16, 2023, 09:14

The exception below probably occurs because [this list ](https://gitlab.inesctec.pt/interconnect/knowledge-engine/-/blob/master/smart-connector/src/main/java/eu/knowledge/engine/smartconnector/runtime/messaging/MessageDispatcher.java#L77)is not concurrency proof. We could replace it blindly with a concurrent list like `List list = Collections.synchronizedList(new LinkedList(...));`. See also [here](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedList.html).

```
traceability-demo-app-pie-1  | 2023-06-16 09:08:09:115 +0000 [qtp961067427-66] INFO MessageDispatcher - I can now deliver the message I received from http://example.org/certificate-kb
traceability-demo-app-pie-1  | 2023-06-16 09:08:09:177 +0000 [qtp961067427-66] WARN ServletHandler -
traceability-demo-app-pie-1  | javax.servlet.ServletException: java.util.ConcurrentModificationException
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.Server.handle(Server.java:497)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
traceability-demo-app-pie-1  |  at java.base/java.lang.Thread.run(Thread.java:833)
traceability-demo-app-pie-1  | Caused by: java.util.ConcurrentModificationException
traceability-demo-app-pie-1  |  at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
traceability-demo-app-pie-1  |  at java.base/java.util.LinkedList$ListItr.remove(LinkedList.java:925)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.tryDeliverUndeliveredMail(MessageDispatcher.java:315)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.notifySmartConnectorsChanged(MessageDispatcher.java:327)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.updateRemoteKerDataFromPeer(RemoteKerConnection.java:78)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.getRemoteKerDetails(RemoteKerConnection.java:89)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.getRemoteSmartConnectorIds(RemoteKerConnection.java:96)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.getRemoteSmartConnectorIds(RemoteKerConnectionManager.java:204)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.getKnowledgeBaseIds(MessageDispatcher.java:282)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.deliverToLocalSmartConnector(MessageDispatcher.java:231)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteMessageReceiver.handleMessage(RemoteMessageReceiver.java:40)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteMessageReceiver.messagingAskmessagePost(RemoteMessageReceiver.java:57)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.inter_ker.api.MessagingApi.messagingAskmessagePost(MessagingApi.java:88)
traceability-demo-app-pie-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
traceability-demo-app-pie-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
traceability-demo-app-pie-1  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
traceability-demo-app-pie-1  |  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
traceability-demo-app-pie-1  |  ... 18 more
traceability-demo-app-pie-1  | 2023-06-16 09:08:09:198 +0000 [qtp961067427-66] WARN HttpChannel - /messaging/askmessage
traceability-demo-app-pie-1  | javax.servlet.ServletException: java.util.ConcurrentModificationException
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.Server.handle(Server.java:497)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
traceability-demo-app-pie-1  |  at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
traceability-demo-app-pie-1  |  at java.base/java.lang.Thread.run(Thread.java:833)
traceability-demo-app-pie-1  | Caused by: java.util.ConcurrentModificationException
traceability-demo-app-pie-1  |  at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
traceability-demo-app-pie-1  |  at java.base/java.util.LinkedList$ListItr.remove(LinkedList.java:925)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.tryDeliverUndeliveredMail(MessageDispatcher.java:315)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.notifySmartConnectorsChanged(MessageDispatcher.java:327)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.updateRemoteKerDataFromPeer(RemoteKerConnection.java:78)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.getRemoteKerDetails(RemoteKerConnection.java:89)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.getRemoteSmartConnectorIds(RemoteKerConnection.java:96)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.getRemoteSmartConnectorIds(RemoteKerConnectionManager.java:204)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.getKnowledgeBaseIds(MessageDispatcher.java:282)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.deliverToLocalSmartConnector(MessageDispatcher.java:231)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteMessageReceiver.handleMessage(RemoteMessageReceiver.java:40)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteMessageReceiver.messagingAskmessagePost(RemoteMessageReceiver.java:57)
traceability-demo-app-pie-1  |  at eu.knowledge.engine.smartconnector.runtime.messaging.inter_ker.api.MessagingApi.messagingAskmessagePost(MessagingApi.java:88)
traceability-demo-app-pie-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
traceability-demo-app-pie-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
traceability-demo-app-pie-1  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
traceability-demo-app-pie-1  |  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
traceability-demo-app-pie-1  |  at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
traceability-demo-app-pie-1  |  ... 18 more
traceability-demo-app-pie-1  | 2023-06-16 09:08:09:226 +0000 [qtp961067427-66] WARN HttpChannel - Could not send response error 500: javax.servlet.ServletException: java.util.ConcurrentModificationException
```

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Oct 24, 2023, 13:23

After replacing it blindly with a synchronized list, the error still occurred because we were iterating over this list while another thread removed/added items from it. After making the iterating better, the error disappeared. These changes are released with version `1.2.2` of the Knowledge Engine.

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Dec 5, 2023, 13:52

Apparently, the issue is still not solved, because we are still modifying the list while iterating it.

The MessageDispatcher keeps a list of undelivered messages that might be delivered at a later moment when a particular problem has been solved. However, this list is not entirely thread-safe (although we already tried to solve this error before), because it might still be modified by another thread [while iterating it](https://gitlab.inesctec.pt/interconnect/knowledge-engine/-/blob/master/smart-connector/src/main/java/eu/knowledge/engine/smartconnector/runtime/messaging/MessageDispatcher.java?ref_type=heads#L315). In that scenario, the following error occurs:

```
nl-pilot-test-ov-pilot-ker-1  | javax.servlet.ServletException: java.util.ConcurrentModificationException
nl-pilot-test-ov-pilot-ker-1  |         at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
nl-pilot-test-ov-pilot-ker-1  |         at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
nl-pilot-test-ov-pilot-ker-1  |         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
nl-pilot-test-ov-pilot-ker-1  |         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
nl-pilot-test-ov-pilot-ker-1  |         at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.Server.handle(Server.java:516)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
nl-pilot-test-ov-pilot-ker-1  |         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
nl-pilot-test-ov-pilot-ker-1  |         at java.base/java.lang.Thread.run(Thread.java:833)
nl-pilot-test-ov-pilot-ker-1  | Caused by: java.util.ConcurrentModificationException
nl-pilot-test-ov-pilot-ker-1  |         at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
nl-pilot-test-ov-pilot-ker-1  |         at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.tryDeliverUndeliveredMail(MessageDispatcher.java:315)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.notifySmartConnectorsChanged(MessageDispatcher.java:333)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.updateRemoteKerDataFromPeer(RemoteKerConnection.java:148)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.getRemoteKerDetails(RemoteKerConnection.java:164)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.getRemoteSmartConnectorIds(RemoteKerConnection.java:185)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.getRemoteSmartConnectorIds(RemoteKerConnectionManager.java:218)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.getKnowledgeBaseIds(MessageDispatcher.java:285)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.tryDeliverUndeliveredMail(MessageDispatcher.java:316)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.notifySmartConnectorsChanged(MessageDispatcher.java:333)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.updateRemoteKerDataFromPeer(RemoteKerConnection.java:148)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.getRemoteKerDetails(RemoteKerConnection.java:164)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.getRemoteSmartConnectorIds(RemoteKerConnection.java:185)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.getRemoteSmartConnectorIds(RemoteKerConnectionManager.java:218)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.getKnowledgeBaseIds(MessageDispatcher.java:285)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.deliverToLocalSmartConnector(MessageDispatcher.java:234)
nl-pilot-test-ov-pilot-ker-1  |         at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteMessageReceiver.handleMessage(RemoteMessageReceiver.java:40)
```

Maybe this is a solution? https://stackoverflow.com/a/12410306

**Comment by Sophietje** [comment]
In GitLab by @sophie.lathouwers.tno.nl on Dec 13, 2023, 08:55

created branch [`422-the-concurrentmodificationexception-in-messagedispatcher-should-not-occur`](/interconnect/knowledge-engine/-/compare/master...422-the-concurrentmodificationexception-in-messagedispatcher-should-not-occur) to address this issue

**Comment by Sophietje** [comment]
In GitLab by @sophie.lathouwers.tno.nl on Dec 15, 2023, 10:36

mentioned in commit f7fddcec35716293e80d711b0ebb07d2ae233ff0
