### ISSUE TITLE
Improve logging when KB is stopped and its open handle requests are cancelled.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#453]
In GitLab by @barry.nouwt.tno.nl on Dec 1, 2023, 14:34

Currently, it gives a (series of) exceptions like this:

```
2023-12-01 08:18:20:774 +0000 [Timer-109617] ERROR RestKnowledgeBase - An exception has occured while reacting
java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.CompletableFuture.cancel(Unknown Source)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.lambda$cancelAndClearAllHandleRequests$10(RestKnowledgeBase.java:717)
	at java.base/java.util.concurrent.ArrayBlockingQueue.forEach(Unknown Source)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.cancelAndClearAllHandleRequests(RestKnowledgeBase.java:716)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.stop(RestKnowledgeBase.java:712)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.suspend(RestKnowledgeBase.java:803)
	at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase$3.run(RestKnowledgeBase.java:786)
	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
	at java.base/java.util.TimerThread.run(Unknown Source)
```

And this might be a bit verbose and confusing, so maybe move the exception to debug level and give a WARN instead of ERROR?

**Comment by Sophietje** [comment]
In GitLab by @sophie.lathouwers.tno.nl on Dec 8, 2023, 09:32

created branch [`439-improve-logging-when-kb-is-stopped-and-its-open-handle-requests-are-cancelled`](/interconnect/knowledge-engine/-/compare/master...439-improve-logging-when-kb-is-stopped-and-its-open-handle-requests-are-cancelled) to address this issue

**Comment by Sophietje** [comment]
In GitLab by @sophie.lathouwers.tno.nl on Dec 12, 2023, 08:22

mentioned in commit 4fdecb37a103d4c99863dcc3517bd903cc4018c4
