### ISSUE TITLE
Improve logging of "The SmartConnector cannot be used anymore once it is stopped" this error.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#456]
In GitLab by @barry.nouwt.tno.nl on Dec 17, 2023, 12:03

Whenever a KB is being used (via the REST API) but it is already stopping, the following Exception is logged:

```
2023-12-17 11:47:20:786 +0000 [qtp1109371569-162744] WARN HttpChannel - /rest/sc/ki
javax.servlet.ServletException: java.lang.IllegalStateException: The SmartConnector cannot be used anymore once it is stopped
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: The SmartConnector cannot be used anymore once it is stopped
        at eu.knowledge.engine.smartconnector.impl.SmartConnectorImpl.checkStopped(SmartConnectorImpl.java:475)
        at eu.knowledge.engine.smartconnector.impl.SmartConnectorImpl.register(SmartConnectorImpl.java:238)
        at eu.knowledge.engine.rest.api.impl.RestKnowledgeBase.register(RestKnowledgeBase.java:460)
        at eu.knowledge.engine.rest.api.impl.KnowledgeInteractionLifeCycleApiServiceImpl.scKiPost(KnowledgeInteractionLifeCycleApiServiceImpl.java:70)
        at eu.knowledge.engine.rest.api.KnowledgeInteractionLifeCycleApi.scKiPost(KnowledgeInteractionLifeCycleApi.java:99)
        at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
```

Maybe it is not necessary to log the full exception on this event, but only give a warning with the Knowledge Base Id for which it happened? This probably happens when a SC is suspended and the user does not know that and still tries to use it anyway, this happens sometimes when people do not fully understand the REST API fully.

**Comment by Sophietje** [comment]
In GitLab by @sophie.lathouwers.tno.nl on Dec 19, 2023, 10:43

created branch [`442-improve-logging-of-the-smartconnector-cannot-be-used-anymore-once-it-is-stopped-this-error`](/interconnect/knowledge-engine/-/compare/master...442-improve-logging-of-the-smartconnector-cannot-be-used-anymore-once-it-is-stopped-this-error) to address this issue

**Comment by Sophietje** [comment]
In GitLab by @sophie.lathouwers.tno.nl on Jan 8, 2024, 10:23

mentioned in commit 9ad1ba2b98de71341669555d4dce3b2d3d126fc6
