### ISSUE TITLE
The `KE_RUNTIME_EXPOSED_URL` should include the URL schema `https://`

### ISSUE THREAD

**Issue by bnouwt** [TNO/knowledge-engine#474]
When a KE Runtime misconfigured its `KE_RUNTIME_EXPOSED_URL` by not including the URL schema, the following exception occurs in the logs of other KERs:

```
cgtest-knowledge-engine-runtime-1  | 2024-02-02 10:28:43:116 +0000 [qtp1541249786-37549] WARN RemoteMessageReceiver - Error while handling incoming message
cgtest-knowledge-engine-runtime-1  | java.lang.IllegalArgumentException: URI with undefined scheme
cgtest-knowledge-engine-runtime-1  |    at java.net.http/jdk.internal.net.http.common.Utils.newIAE(Utils.java:286)
cgtest-knowledge-engine-runtime-1  |    at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.checkURI(HttpRequestBuilderImpl.java:79)
cgtest-knowledge-engine-runtime-1  |    at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.<init>(HttpRequestBuilderImpl.java:55)
cgtest-knowledge-engine-runtime-1  |    at java.net.http/java.net.http.HttpRequest.newBuilder(HttpRequest.java:305)
cgtest-knowledge-engine-runtime-1  |    at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.updateRemoteKerDataFromPeer(RemoteKerConnection.java:121)
cgtest-knowledge-engine-runtime-1  |    at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.getRemoteKerDetails(RemoteKerConnection.java:164)
cgtest-knowledge-engine-runtime-1  |    at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnection.getRemoteSmartConnectorIds(RemoteKerConnection.java:185)
cgtest-knowledge-engine-runtime-1  |    at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteKerConnectionManager.getRemoteSmartConnectorIds(RemoteKerConnectionManager.java:218)
cgtest-knowledge-engine-runtime-1  |    at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.getKnowledgeBaseIds(MessageDispatcher.java:290)
cgtest-knowledge-engine-runtime-1  |    at eu.knowledge.engine.smartconnector.runtime.messaging.MessageDispatcher.deliverToLocalSmartConnector(MessageDispatcher.java:231)
cgtest-knowledge-engine-runtime-1  |    at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteMessageReceiver.handleMessage(RemoteMessageReceiver.java:40)
cgtest-knowledge-engine-runtime-1  |    at eu.knowledge.engine.smartconnector.runtime.messaging.RemoteMessageReceiver.messagingAskmessagePost(RemoteMessageReceiver.java:57)
cgtest-knowledge-engine-runtime-1  |    at eu.knowledge.engine.smartconnector.runtime.messaging.inter_ker.api.MessagingApi.messagingAskmessagePost(MessagingApi.java:88)
cgtest-knowledge-engine-runtime-1  |    at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
cgtest-knowledge-engine-runtime-1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cgtest-knowledge-engine-runtime-1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
cgtest-knowledge-engine-runtime-1  |    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.Server.handle(Server.java:516)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
cgtest-knowledge-engine-runtime-1  |    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
cgtest-knowledge-engine-runtime-1  |    at java.base/java.lang.Thread.run(Thread.java:840)
```

This issue possibly has multiple parts:
- [x] Update our documentation that `KE_RUNTIME_EXPOSED_URL` should include the URL schema like `https://`
- [x] Make sure other KERs do not break when a single KER misconfigures its `KE_RUNTIME_EXPOSED_URL`.
- [x] Add a check to the KE_RUNTIME_EXPOSED_URL to prevent KERs from starting with this misconfiguration.

**Comment by bnouwt** [comment]
Additionally, the `KE_RUNTIME_EXPOSED_URL` value should not end with a slash. So, for example:

```
KE_RUNTIME_EXPOSED_URL=https://www.knowledge-engine.eu/ker/
```
is incorrect and 

```
KE_RUNTIME_EXPOSED_URL=https://www.knowledge-engine.eu/ker
```

is correct.

**Comment by bnouwt** [comment]
Part 1 above is [already covered](https://github.com/TNO/knowledge-engine/blob/master/docs/04_distributed_mode.md?plain=1#L29).

**Comment by bnouwt** [comment]
For part 2 above there are different invalid URLs that cause different problems:

- runtime-3:8081, test.runtime.nl:8081: In Knowledge Directory log: javax.servlet.ServletException: java.lang.RuntimeException: Encountered invalid URI syntax while stripping userinfo from URI.
- 3test.runtime.nl:8081: In misconfigured KER log: java.net.URISyntaxException: Illegal character in scheme name at index 0: 3esynaptiq.ngrok.app:8081
- 3test.runtime.nl: In other KER: java.lang.IllegalArgumentException: URI with undefined scheme
- http://runtime-3:8081/: In other KER: Failed to receive runtimedetails from http://runtime-3:8081/, got status code 404. Trying KER again in 1 minutes.
- runtime-3: In other KER: java.lang.IllegalArgumentException: URI with undefined scheme

Maybe add unit tests for some of these?
