### ISSUE TITLE
Unable to run the KD version 1.2.4

### ISSUE THREAD

**Issue by aandraz** [TNO/knowledge-engine#495]
The service is running on the Kubernetes env. There is no problem with the 1.2.2.

> [main] INFO eu.knowledge.engine.knowledgedirectory.KnowledgeDirectory - Starting Knowledge Directory REST API on port 8282.
[main] INFO org.eclipse.jetty.server.Server - jetty-11.0.15; built: 2023-04-11T18:37:53.775Z; git: 5bc5e562c8d05c5862505aebe5cf83a61bdbcb96; jvm 21.0.2+13-LTS
Mar 04, 2024 2:26:43 PM org.glassfish.jersey.server.wadl.WadlFeature configure
WARNING: JAXBContext implementation could not be found. WADL feature is disabled.
[main] ERROR eu.knowledge.engine.knowledgedirectory.Main - Error starting server
java.lang.NoClassDefFoundError: jakarta/validation/Validator
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvokerConfigurator.postInit(ResourceMethodInvokerConfigurator.java:53)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$2(ApplicationHandler.java:366)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4305)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:366)
        at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:310)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
        at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:309)
        at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:274)
        at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
        at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:338)
        at jakarta.servlet.GenericServlet.init(GenericServlet.java:178)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:633)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415)
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$2(ServletHandler.java:725)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:749)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:902)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
        at org.eclipse.jetty.server.Server.start(Server.java:470)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
        at org.eclipse.jetty.server.Server.doStart(Server.java:415)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at eu.knowledge.engine.knowledgedirectory.KnowledgeDirectory.start(KnowledgeDirectory.java:49)
        at eu.knowledge.engine.knowledgedirectory.Main.main(Main.java:28)
Caused by: java.lang.ClassNotFoundException: jakarta.validation.Validator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 45 more
[main] INFO org.eclipse.jetty.server.Server - Stopped Server@340f438e{STOPPING}[11.0.15,sto=0]
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@162be91c{/,null,STOPPED}

**Comment by bnouwt** [comment]
Hey @aandraz, thanks for reporting this issue. Not sure why the exception only occurs in the docker image and not in our development environment, but its clear we need some additional testing to prevent this in the future 👍 . 

A work around should be to keep using the previous `1.2.3` version.

Two actions:
- [ ] add simple knowledge directory docker image test
- [ ] solve dependency issue

**Comment by bnouwt** [comment]
Dependency bug solved. Check if and how we can design a test to prevent this from happening in the future.

**Comment by bnouwt** [comment]
This issue can be merged. I've double checked whether both the `jar-with-dependencies` and the docker image constructed from the fixed knowledge-directory start without the error above and this is the case. Also double checked whether running 3 KERs that point towards the fixed knowledge directory works correctly and it does.
