### ISSUE TITLE
testPostReact sometimes fails.

### ISSUE THREAD

**Issue by Sophietje** [TNO/knowledge-engine#95]
In GitLab by @barry.nouwt.tno.nl on Jan 26, 2021, 14:53

[pool-2-thread-1] ERROR nl%2Fkb1-SmartConnectorImpl - KnowledgeBase threw exception
java.lang.ClassCastException: class interconnect.ke.api.interaction.PostKnowledgeInteraction cannot be cast to class interconnect.ke.api.interaction.AskKnowledgeInteraction (interconnect.ke.api.interaction.PostKnowledgeInteraction and interconnect.ke.api.interaction.AskKnowledgeInteraction are in unnamed module of loader 'app')
	at interconnect.ke.sc.SerialMatchingProcessor.checkOtherKnowledgeInteraction(SerialMatchingProcessor.java:74)
	at interconnect.ke.sc.SerialMatchingProcessor.checkOtherKnowledgeInteraction(SerialMatchingProcessor.java:135)
	at interconnect.ke.sc.SerialMatchingProcessor.processPostInteraction(SerialMatchingProcessor.java:63)
	at interconnect.ke.sc.InteractionProcessorImpl.processPostFromKnowledgeBase(InteractionProcessorImpl.java:141)
	at interconnect.ke.sc.SmartConnectorImpl.post(SmartConnectorImpl.java:382)
	at interconnect.ke.sc.SmartConnectorImpl.post(SmartConnectorImpl.java:398)
	at interconnect.ke.api.TestPostReact$1.waitForOtherKbAndPostSomething(TestPostReact.java:72)
	at interconnect.ke.api.TestPostReact$1.smartConnectorReady(TestPostReact.java:49)
	at interconnect.ke.sc.SmartConnectorImpl.lambda$2(SmartConnectorImpl.java:448)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by Sophietje** [comment]
In GitLab by @barry.nouwt.tno.nl on Jan 29, 2021, 15:20


Another error in postReact. This one is probably caused by there not being any bindings in the react message, because there is no result graph pattern. Do we want to send a react message then?

```
java.lang.NullPointerException
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:335)
	at interconnect.ke.sc.SerialMatchingProcessor.lambda$1(SerialMatchingProcessor.java:118)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
	at interconnect.ke.sc.MessageRouterImpl.handleReactMessage(MessageRouterImpl.java:152)
	at interconnect.ke.runtime.JvmOnlyMessageDispatcher$SmartConnectorHandler.lambda$0(JvmOnlyMessageDispatcher.java:67)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
